### ISSUE TITLE
Auto-completion not working in subsequent cell

### ISSUE THREAD

**Issue by vpankaj97** [MicrosoftDocs/intellicode#234] opened 2020-10-11 15:05 UTC
Issue Type: <b>Bug</b>

Failure to load auto-completion of any imported module (be it RANDOM, SYS, OS) only on the subsequent cells.

i.e. In the same cell as I import the module, auto-completion works. But as soon as I jump to the next cell, auto-completion fails.

On WSL1 - Ubuntu 18.04
Python Version - (daily dev channel)
Using Python Preview Notebook editor
Extension version: 1.2.10
VS Code version: Code - Insiders 1.51.0-insider (f5d3ba4d61146b78f0c75c82f3f85232d3409bc1, 2020-10-09T05:34:54.647Z)
OS version: Windows_NT x64 10.0.19041
Remote OS version: Linux x64 4.4.0-19041-Microsoft

![Working Fine](https://user-images.githubusercontent.com/49087486/95682067-e9fae780-0c00-11eb-9ce6-0457109f461f.png)
![Fails](https://user-images.githubusercontent.com/49087486/95682074-eff0c880-0c00-11eb-82d9-7a96b8600ecb.png)

**Comment by catycaldwell** [comment] 2020-10-12 18:50
+ @savannahostrowski + @jakebailey We'd like to transfer to the Pylance team to review as we are not sure this is an Intellicode problem. Can Claudia, Savannah triage this Notebook issue?

**Comment by jakebailey** [comment] 2020-10-12 18:54
This is likely microsoft/vscode-python#13190, as they are using the new notebooks view which doesn't behave properly with language servers.

**Comment by jakebailey** [comment] 2020-10-12 19:02
microsoft/vscode-python#14364

**Comment by catycaldwell** [comment] 2020-10-12 19:21
Closing as duplicate of [microsoft/vscode-python#14364](https://github.com/microsoft/vscode-python/issues/14364)

**Closed by catycaldwell** 2020-10-12 19:21 UTC
Labels: python, vscode, vscode-python
