### ISSUE TITLE
[VS Code] JS/TS order of IntelliCode suggestions bug

### ISSUE THREAD

**Issue by svipas** [MicrosoftDocs/intellicode#56] opened 2019-01-29 18:40 UTC
**Product and Version** [VS/VSCode]: VS Code
**OS Version** [macOS/Windows]: macOS latest
**IntelliCode Extension Version**: 1.1.2
**Target Platform or Language** [e.g. Node.js]: JS/TS

Sometimes I get this:

<img width="782" alt="screenshot 2019-01-28 at 08 24 00" src="https://user-images.githubusercontent.com/10441177/51818095-3475ec80-22d6-11e9-90aa-ef068bcb1d4a.png">

**Comment by svipben** [comment] 2019-01-29 18:40
I'm separating issues from #53

**Comment by svipben** [comment] 2019-01-29 18:48
**How to reproduce?**

1. Create an empty untitled file of JS or TS type.
2. Look at my picture below and do everything in order and in the last one you should get order bug.

As you can see everything is OK, now select `big` from the list.
<img width="396" alt="screen shot 2019-01-29 at 20 46 09" src="https://user-images.githubusercontent.com/10441177/51932058-07752700-2407-11e9-89c1-dfae43ec52c0.png">

As you can see order is mixed, it should keep IntelliCode suggestions at the top, but instead we get `big` at the top.
<img width="396" alt="screen shot 2019-01-29 at 20 46 55" src="https://user-images.githubusercontent.com/10441177/51932097-1956ca00-2407-11e9-9d4c-54dd5761f316.png">

**Comment by jkeech** [comment] 2019-04-17 20:34
@svipas, can you still reproduce this with the latest version of IntelliCode? I haven't been able to reproduce this locally.

**Comment by svipas** [comment] 2019-04-18 06:25
@jkeech I'm not using anymore IntelliCode :( But I recently tried it and I saw this issue with `"editor.suggest.localityBonus": true,` in JS.

**Comment by jkeech** [comment] 2019-04-18 16:48
@svipas Thanks for the details! Sorry to hear that you are not using IntelliCode anymore. If you don't mind sharing, I'd love to understand why. Please feel free to send me an email at john.keech@microsoft.com.

--

I'm able to reproduce this with locality bonus turned on if I'm typing within some block scope. The locality bonus seems to be applied by the editor after it recieves the completion list, so it re-sorts the list after IntelliCode has returned the list that it wants presented.

I think this is similar to the `editor.suggestSelection` behavior -- IntelliCode works better with some settings than others. I'm not sure how opinionated we want IntelliCode to be in this case. We will think about potential solutions here. One option is to have IntelliCode turn off the locality bonus, but I'm not sure if that's the best experience for users.

**Comment by svipas** [comment] 2019-04-20 07:09
Even without any context it still mixes order of IntelliCode and IntelliSense auto-completions. So I guess it's not exactly related to locality bonus.

<img width="1552" alt="Screen Shot 2019-04-20 at 09 19 58" src="https://user-images.githubusercontent.com/10441177/56453602-954d1800-634d-11e9-95f1-de9dad5d8141.png">

I'm not using it anymore because I see no reason right now. I disabled suggestions pop-up because I like minimalistic editor which reduces as much noise as possible and I enabled tab completion and if I don't know how exactly property ends, but I know beginning I can simply press Tab and it will be auto-completed. Of course sometimes I trigger suggestions pop-up if I forgot something, but it's not common.

I was really excited about this feature and I subscribed to Microsoft to get a email about this, but after trying it for about 1-2 weeks I see no reason of using it, but this is only my opinion and I believe it's really useful extension for other developers, you guys did a really great job and this may be a future for better auto-completion since you can train it for your own project and get best practices from other projects.

**Comment by jkeech** [comment] 2019-04-22 16:15
Thanks for the feedback! It makes sense in your scenario to not need or want IntelliCode.

**Comment by uniqueiniquity** [comment] 2020-01-29 20:41
@markw-t  I can no longer reproduce this, even with locality bonus enabled, so I'd suggest we close this issue.

**Comment by markw-t** [comment] 2020-01-29 23:02
@svipas, per @uniqueiniquity we're closing this issue out. If anyone is still able to repro this, please open a fresh issue. Thanks!

**Closed by markw-t** 2020-01-29 23:02 UTC
