### ISSUE TITLE
Option to download the model locally and transfer it to the remote instance running VS Code on a host without Internet access over the SSH connection 

### ISSUE THREAD

**Issue by jayBana** [MicrosoftDocs/intellicode#171] opened 2020-02-23 13:27 UTC
**Feature Request for VS Code**

It would be great if there was an option to download the model locally and transfer it to the remote instance running VS Code on a host without Internet access over the SSH connection.

Something similar to the `remote.SSH.allowLocalServerDownload` or the `remote.downloadExtensionsLocally` options that are available in the [vscode-remote extension](https://github.com/microsoft/vscode-remote-release).

A lot of us use VS Code in corporate environments with restricted or no access to the Internet.

**Comment by markw-t** [comment] 2021-04-01 15:48
Reopening due to erroneous bot closure. Apologies for any confusion

**Comment by markw-t** [comment] 2021-04-01 15:49
#102 covers this question, so closing as dupe of that

**Closed by markw-t** 2021-04-01 15:49 UTC
Labels: product-feedback, vscode

**Comment by markw-t** [comment] 2021-05-10 14:53
Thanks Peter; the intent of #102 is to cover all possible scenarios where users might want an offline ability to use IntelliCode's base completions by means of some sort of download. We don't yet have support for this but that issue is meant to collect all the votes for such a capability in one place. Does that make sense?
