### ISSUE TITLE
IntelliCode Completions not working with Python

### ISSUE THREAD

**Issue by Pasu4** [MicrosoftDocs/intellicode#537] opened 2024-01-29 08:11 UTC
**Product and Version**: VSCode
**OS Version**: Windows
**IntelliCode Extension Version**: IntelliCode v1.2.30; IntelliCode Completions v1.0.22
**Target Platform or Language**: Python

**Steps to Reproduce / Scenario:**

1. Install Python, IntelliCode and IntelliCode Completions.
2. Create a new `.py` file.

The console then shows the following output for IntelliCode Completions:

```
Worker 1 has been created
[Worker thread] Worker 1 has started
[Worker thread] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Worker thread] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Worker thread] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Worker thread] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Worker thread] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Worker thread] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Worker thread] Unhandled rejection error: fetch failed
[Worker thread] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Worker thread] Unhandled rejection error: fetch failed
[Worker thread] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Extension version: 1.0.22 034a5c7
```

No gray code completions are shown in the editor.

**Comment by vivlimmsft** [comment] 2024-04-04 21:16
This should be fixed by yesterday's update to v2.0.0. (duplicate of #491)
Please reopen or create a new issue if you still see this after updating.

**Closed by vivlimmsft** 2024-04-04 21:16 UTC
Labels: python, vscode-completions
