### ISSUE TITLE
C# support on VS Code and Linux

### ISSUE THREAD

**Issue by PhilParisot** [MicrosoftDocs/intellicode#208] opened 2020-07-10 03:15 UTC
It would truly be awesome if we could get support for C# IntelliCode on Linux!

**Comment by Rhitt01** [comment] 2021-02-13 09:33
and also c++

**Comment by ayim** [comment] 2022-04-04 23:39
Hey folks! This looks like a duplicate of #81, gonna merge these votes into that item if it's cool with y'all!

**Comment by ayim** [comment] 2022-04-04 23:39
-

**Closed by ayim** 2022-04-04 23:39 UTC
Labels: product-feedback, vscode, C#
