### ISSUE TITLE
No suggestions when using TS workspace version (3.1.6) instead of VS version (3.1.4)

### ISSUE THREAD

**Issue by opus131** [MicrosoftDocs/intellicode#32] opened 2018-12-07 12:46 UTC
**Product and Version**: VSCode 1.29.1
**OS Version**: Windows 10 (64bit)
**IntelliCode Extension Version**: 1.1.0
**Target Platform or Language**: nodejs

**Steps to Reproduce / Scenario:**

1. Configure project to use a higher TS version than the currently shipped one (which is 3.1.4)
2. See it not working

I'd understand smth like "works only for TS X.Y.Z or higher" due to missing features in older versions - but why does it not work if the workspace version is **newer**?

**Comment by jkeech** [comment] 2018-12-07 18:52
@minestarks do you know why this happens? Is it due to the way IntelliCode plugins extend the language server? During activation, do have the ability to know which TS instance is being used and activate the plugin in the correct instance?

**Comment by jkeech** [comment] 2018-12-07 18:53
FWIW, this seems like a duplicate of #23

**Comment by minestarks** [comment] 2018-12-07 21:11
It is a duplicate. I'll close the other one in favor of this one since this one has a more searchable title.  https://github.com/MicrosoftDocs/intellicode/issues/23#issuecomment-445059609

Unfortunately, we lack a bit of infrastructure in VS Code and TypeScript to be able to determine version compatibility between TS and the plugin, therefore we simply disable all global plugins when using a workspace TS server.

https://github.com/Microsoft/TypeScript/issues/19224 and https://github.com/Microsoft/TypeScript/issues/18849 track some of the work that needs to happen here.

**Comment by minestarks** [comment] 2018-12-07 21:12
https://github.com/MicrosoftDocs/intellicode/issues/23#issuecomment-445059609

We root caused this to the fact that the IntelliCode plugin doesn't load when using a TypeScript version from the workspace instead of VS Code's own version. 

You can work around this for now by choosing to use TypeScript from VS Code and not the workspace:

![image](https://user-images.githubusercontent.com/16928427/49616694-89485700-f966-11e8-9ec8-96c254dbe2e8.png)

**Comment by jasonswearingen** [comment] 2019-03-27 23:47
@minestarks  fyi I am getting the same problem, but using VSCode and it's built-in typescript (v3.3.3).  I disabled all extensions except intellicode (latest, v1.1.5) and then in the extension log output I see the following.  


<details><summary>(click me for log)</summary>

```console
[2019-03-27 13:34:02.340] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-03-27 13:34:02.345] [exthost] [error] Error: TypeScript Server Error (3.3.3)
Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getFixesInfoForNonUMDImport (tsserver.js:112198:22)
    at getFixesInfo (tsserver.js:112140:50)
    at Object.getCodeActions (tsserver.js:111902:28)
    at tsserver.js:109601:121
    at Object.flatMap (tsserver.js:504:25)
    at Object.getFixes (tsserver.js:109601:23)
    at tsserver.js:118807:35
    at Object.flatMap (tsserver.js:504:25)
    at Object.getCodeFixesAtPosition (tsserver.js:118805:23)
    at TSLintPlugin.getCodeFixesAtPosition (C:\Users\jason\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0\node_modules\typescript-tslint-plugin\out\plugin.js:143:34)
    at Proxy.intercept.getCodeFixesAtPosition.args (C:\Users\jason\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0\node_modules\typescript-tslint-plugin\out\plugin.js:75:25)
    at TSLintPlugin.getCodeFixesAtPosition (C:\Users\jason\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0\node_modules\typescript-tslint-plugin\out\plugin.js:143:34)
    at Proxy.intercept.getCodeFixesAtPosition.args (C:\Users\jason\.vscode\extensions\ms-vscode.vscode-typescript-tslint-plugin-1.0.0\node_modules\typescript-tslint-plugin\out\plugin.js:75:25)
    at IOSession.Session.getCodeFixes (tsserver.js:126958:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125763:61)
    at tsserver.js:127127:88
    at IOSession.Session.executeWithRequestId (tsserver.js:127118:28)
    at IOSession.Session.executeCommand (tsserver.js:127127:33)
    at IOSession.Session.onMessage (tsserver.js:127149:35)
    at Interface.<anonymous> (tsserver.js:128410:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at Function.create (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:173419)
	at v.dispatchResponse (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:178725)
	at v.dispatchMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:177477)
	at constructor._reader.onData.e (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:176833)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:254)
	at t.Reader.onLengthData (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:182693)
	at Socket.t.Reader.constructor.e.on.e (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:182341)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-27 13:34:33.562] [exthost] [error] [vscode.typescript-language-features] provider FAILED
[2019-03-27 13:34:33.562] [exthost] [error] Error: TypeScript Server Error (3.3.3)
Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at Object.getSymbolDisplayPartsDocumentationAndSymbolKind (tsserver.js:105510:44)
    at tsserver.js:96998:41
    at Object.runWithCancellationToken (tsserver.js:31173:28)
    at createCompletionDetailsForSymbol (tsserver.js:96997:30)
    at Object.getCompletionEntryDetails (tsserver.js:96979:28)
    at Proxy.getCompletionEntryDetails (tsserver.js:118507:35)
    at C:\Users\jason\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.1.5\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:1:6957
    at Proxy.o.getCompletionEntryDetails (C:\Users\jason\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.1.5\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:1:7105)
    at C:\Users\jason\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.1.5\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:1:6957
    at Object.o.getCompletionEntryDetails (C:\Users\jason\.vscode\extensions\visualstudioexptteam.vscodeintellicode-1.1.5\node_modules\@vsintellicode\typescript-intellicode-plugin\lib\index.js:1:7105)
    at tsserver.js:126665:57
    at Object.mapDefined (tsserver.js:601:30)
    at IOSession.Session.getCompletionEntryDetails (tsserver.js:126663:33)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (tsserver.js:125648:61)
    at tsserver.js:127127:88
    at IOSession.Session.executeWithRequestId (tsserver.js:127118:28)
    at IOSession.Session.executeCommand (tsserver.js:127127:33)
    at IOSession.Session.onMessage (tsserver.js:127149:35)
    at Interface.<anonymous> (tsserver.js:128410:27)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
    at Socket.ondata (readline.js:149:10)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:636:20)
	at Function.create (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:173419)
	at v.dispatchResponse (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:178725)
	at v.dispatchMessage (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:177477)
	at constructor._reader.onData.e (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:176833)
	at u.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:43:254)
	at t.Reader.onLengthData (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:182693)
	at Socket.t.Reader.constructor.e.on.e (c:\Program Files\Microsoft VS Code\resources\app\extensions\typescript-language-features\dist\extension.js:1:182341)
	at Socket.emit (events.js:182:13)
	at Socket.EventEmitter.emit (domain.js:442:20)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-03-27 13:35:55.643] [exthost] [info] extension host started
```

</details>

this is with vscode 1.32.3

**Comment by jkeech** [comment] 2019-03-27 23:52
@jasonswearingen The first error in your log looks like it's coming from TSLint (`at TSLintPlugin.getCodeFixesAtPosition`), but the second one is originating from IntelliCode. It looks like the exception (in both cases) is happening on the TS language server though, so I'm not sure whether this is an IntelliCode bug or a TS language server bug just by looking at the callstack.

@minestarks / @uniqueiniquity, have you seen this before?

**Comment by jasonswearingen** [comment] 2019-03-28 00:08
sorry, even though I choose "clear output" it reloaded all those old logs.    It looks like no new errors were spit out, but still no intellicode support is working.

i'll try turning on verbose logging, and will update this post in a few minutes with the "real" log.

**Comment by kkorus** [comment] 2019-05-24 09:25
Same here, switching to VS Code TypeScript version helped.

**Comment by Blasz** [comment] 2019-10-22 23:44
I'm getting a similar issue, however, the logs report that the global plugin cannot be resolved locally.

`
Failed to load module '@vsintellicode/typescript-intellicode-plugin' from /Users/me/project/node_modules/node_modules: Error: Could not resolve JS module '@vsintellicode/typescript-intellicode-plugin' starting at '/Users/me/project/node_modules/node_modules'
`.

When loading from vscode's TS version we get:

```
Info 28   [17:21:35.763] Loading global plugin @vsintellicode/typescript-intellicode-plugin
Info 29   [17:21:35.763] Enabling plugin @vsintellicode/typescript-intellicode-plugin from candidate paths: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../..,/Users/me/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.0
Info 30   [17:21:35.763] Loading @vsintellicode/typescript-intellicode-plugin from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js/../../.. (resolved to /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/node_modules)
Info 31   [17:21:35.779] Loading @vsintellicode/typescript-intellicode-plugin from /Users/me/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.0 (resolved to /Users/me/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.0/node_modules)
```

VS/OS info:

Version: 1.39.1
Commit: 88f15d1
Date: 2019-10-10T23:35:11.314Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

**Comment by koistya** [comment] 2020-09-17 13:52
```
Failed to load module '@vsintellicode/typescript-intellicode-plugin' from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/node_modules: Error: Could not resolve JS module '@vsintellicode/typescript-intellicode-plugin' starting at '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/node_modules'. Looked in: 
    at Object.resolveJSModule (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:38253:19)
    at Object.sys.require (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:157662:45)
    at Function.Project.resolveModule (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:147790:35)
    at ./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:148867:36
    at Object.firstDefined (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:218:26)
    at InferredProject.Project.enablePlugin (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:148866:41)
    at _loop_2 (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:148850:32)
    at InferredProject.Project.enableGlobalPlugins (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:148856:25)
    at new InferredProject (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:149042:23)
    at ProjectService.createInferredProject (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:151263:31)
    at ProjectService.getOrCreateInferredProjectForProjectRootPathIfEnabled (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:151201:33)
    at ProjectService.assignOrphanScriptInfoToInferredProject (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:150439:36)
    at ProjectService.assignProjectToOpenedScriptInfo (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:151974:26)
    at ./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:152231:97
    at Object.flatMap (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:513:25)
    at ProjectService.applyChangesInOpenFiles (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:152231:41)
    at Session.handlers.ts.Map.ts.getEntries._a.<computed> (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:153250:46)
    at ./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:155122:88
    at IOSession.Session.executeWithRequestId (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:155113:28)
    at IOSession.Session.executeCommand (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:155122:33)
    at IOSession.Session.onMessage (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:155146:35)
    at IOSession.onMessage (./.yarn/sdks/typescript/lib/tsserver.js:24:32)
    at Interface.<anonymous> (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:157362:27)
    at Interface.emit (events.js:223:5)
    at Interface._onLine (readline.js:315:10)
    at Interface._normalWrite (readline.js:460:12)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

**Comment by tobiasletcher-ap** [comment] 2020-10-12 13:12
> Using a workspace version of TypeScript `4.0.2-pnpify` with Yarn `2.2.2`.
> 
> ```
> Failed to load module '@vsintellicode/typescript-intellicode-plugin' from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/node_modules: Error: Could not resolve JS module '@vsintellicode/typescript-intellicode-plugin' starting at '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/node_modules'. Looked in: 
>     at Object.resolveJSModule (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:38253:19)
>     at Object.sys.require (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:157662:45)
>     at Function.Project.resolveModule (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:147790:35)
>     at ./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:148867:36
>     at Object.firstDefined (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:218:26)
>     at InferredProject.Project.enablePlugin (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:148866:41)
>     at _loop_2 (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:148850:32)
>     at InferredProject.Project.enableGlobalPlugins (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:148856:25)
>     at new InferredProject (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:149042:23)
>     at ProjectService.createInferredProject (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:151263:31)
>     at ProjectService.getOrCreateInferredProjectForProjectRootPathIfEnabled (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:151201:33)
>     at ProjectService.assignOrphanScriptInfoToInferredProject (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:150439:36)
>     at ProjectService.assignProjectToOpenedScriptInfo (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:151974:26)
>     at ./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:152231:97
>     at Object.flatMap (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:513:25)
>     at ProjectService.applyChangesInOpenFiles (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:152231:41)
>     at Session.handlers.ts.Map.ts.getEntries._a.<computed> (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:153250:46)
>     at ./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:155122:88
>     at IOSession.Session.executeWithRequestId (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:155113:28)
>     at IOSession.Session.executeCommand (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:155122:33)
>     at IOSession.Session.onMessage (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:155146:35)
>     at IOSession.onMessage (./.yarn/sdks/typescript/lib/tsserver.js:24:32)
>     at Interface.<anonymous> (./.yarn/cache/typescript-patch-edef266e49-b8b689ef99.zip/node_modules/typescript/lib/tsserver.js:157362:27)
>     at Interface.emit (events.js:223:5)
>     at Interface._onLine (readline.js:315:10)
>     at Interface._normalWrite (readline.js:460:12)
>     at Socket.ondata (readline.js:172:10)
>     at Socket.emit (events.js:223:5)
>     at addChunk (_stream_readable.js:309:12)
>     at readableAddChunk (_stream_readable.js:290:11)
>     at Socket.Readable.push (_stream_readable.js:224:10)
>     at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
> ```
> 
> ![image](https://user-images.githubusercontent.com/197134/93482249-2a1fc080-f908-11ea-81f6-1878684fc780.png)

I had the same issue trying to use typescript@next and typescript@beta. I figured out that the issue was caused by the extension https://marketplace.visualstudio.com/items?itemName=basarat.god. After disabling the extension all is right with the world again.

**Comment by ColCh** [comment] 2020-10-17 11:44
Hey I hacked this to make it work :D

However, I really do not recommend to do that on regular base. Dunno if this would break something.

TL,DR: just link `@vsintellicode` module from user dir (`~/.vscode/`) into global Vscode installation search path (`/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/node_modules`)

I did that with ol' `ln -s`

like this

```
~ $ cd '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/node_modules'
/A/V/C/R/a/e/t/node_modules $ ln -s /Users/colch/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.10/node_modules/@vsintellicode
```

tsserver logs in this case (note paths!)

```
Info 45   [14:41:0.525] Loading global plugin @vsintellicode/typescript-intellicode-plugin
Info 46   [14:41:0.526] Enabling plugin @vsintellicode/typescript-intellicode-plugin from candidate paths: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features,/Users/colch/.vscode/extensions/ms-vscode.vscode-typescript-tslint-plugin-1.2.3,/Users/colch/Documents/Workspace/stonks/node_modules/typescript/lib/tsserver.js/../../..
Info 47   [14:41:0.526] Loading @vsintellicode/typescript-intellicode-plugin from /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features (resolved to /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript-language-features/node_modules)
Info 48   [14:41:0.532] IntelliCode plugin: starting configuration: {"name":"@vsintellicode/typescript-intellicode-plugin","global":true}
Info 49   [14:41:0.533] Plugin validation succeded
```

**Comment by ayim** [comment] 2023-06-16 03:05
Closing due to age and inactivity.

**Closed by ayim** 2023-06-16 03:05 UTC
Labels: bug, product-issue, vscode, JS/TS
