### ISSUE TITLE
Python intellisence not working

### ISSUE THREAD

**Issue by Shibli2316** [MicrosoftDocs/intellicode#343] opened 2022-03-21 16:37 UTC
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.
This issue is popping whenever i am trying to open my python files.

**Comment by alejovelas** [comment] 2022-03-23 16:54
I have the same problem, please say me if you have the solution. tnks

**Comment by markw-t** [comment] 2022-03-23 18:24
Hi @Shibli2316 and @alejovelas . @leti367 can help you investigate this but we need some further information from you.  

Could you please help to provide the logs for both IntelliCode and Python? To get the logs, on VSCode, you can click on 'View' -> 'Output'. Then choose 'VS Intellicode' and 'Python' for logs (just paste the results from each one of them into this issue). 

Also, it would be super helpful if you can provide a little more detail of the exact steps you took to see this issue. Specifically steps after starting VSCode instance and before opening the python file. 

This may be a duplicate of [2500](https://github.com/microsoft/pylance-release/issues/2500) but we need more details to be sure.

Thanks!
Mark

**Comment by alejovelas** [comment] 2022-03-23 21:45
Hello Mark!!!

Thanks for your help. I copy the log you request.


the log of vs IntelliCode:

`Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Error while activating Python: {"errno":-4058,"code":"ENOENT","syscall":"scandir","path":"C:\\Users\\javelasquezc\\AppData\\Local\\Continuum\\anaconda3"}
`
Python log:

`Experiment 'pythonaa' is active
Experiment 'pythonTensorboardExperiment' is active
Experiment 'PythonPyTorchProfiler' is active
Experiment 'pythonDeprecatePythonPath' is active
Experiment 'pythonInterpreterInfoPinned' is active
> conda info --json
> .\AppData\Local\Programs\Python\Python39\python.exe .\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\get_output_via_markers.py .\.vscode\extensions\ms-python.python-2022.2.1924087327\pythonFiles\interpreterInfo.py
[ERROR 2022-2-23 15:40:40.205]: Python Extension: interpreterManager.refresh [Error: ENOENT: no such file or directory, scandir 'C:\Users\javelasquezc\AppData\Local\Continuum\anaconda3'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\javelasquezc\\AppData\\Local\\Continuum\\anaconda3'
}
> .\.conda\Scripts\conda.exe info --json
> .\anaconda.sh\Scripts\conda.exe info --json
> .\AppData\Local\Continuum\anaconda3\envs\py35\Scripts\conda.exe info --json
> .\AppData\Local\Continuum\anaconda3\envs\py39\Scripts\conda.exe info --json
[ERROR 2022-2-23 15:40:51.700]: [
  'Failed to activate a workspace, Class name = f, completed in 16369ms, has a falsy return value, Arg 1: <Uri:c:\\Users\\javelasquezc\\Desktop\\Alejo\\Yo\\Mis documentos\\Platzi\\Ciencia de los datos\\CursoPOOUber\\Python\\UberX.py>, Return Value: undefined',
  [Error: ENOENT: no such file or directory, scandir 'C:\Users\javelasquezc\AppData\Local\Continuum\anaconda3'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'scandir',
    path: 'C:\\Users\\javelasquezc\\AppData\\Local\\Continuum\\anaconda3'
  }
]
[ERROR 2022-2-23 15:40:51.703]: Failure during activation. [Error: ENOENT: no such file or directory, scandir 'C:\Users\javelasquezc\AppData\Local\Continuum\anaconda3'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\javelasquezc\\AppData\\Local\\Continuum\\anaconda3'
}
[ERROR 2022-2-23 15:40:51.703]: sendStartupTelemetry() failed. [Error: ENOENT: no such file or directory, scandir 'C:\Users\javelasquezc\AppData\Local\Continuum\anaconda3'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\javelasquezc\\AppData\\Local\\Continuum\\anaconda3'
}
`

Thanks you!

**Comment by leti367** [comment] 2022-03-23 23:53
@alejovelas, thanks for the logs. Based on the logs, In your case, there's an issue to activate python extension: 
"errno: -4058, code: 'ENOENT', syscall: 'scandir', path: 'C:\\Users\\javelasquezc\\AppData\\Local\\Continuum\\anaconda3'"
Can you help to double check if this directory exits or not?

**Comment by alejovelas** [comment] 2022-03-25 16:54
Hi Leti367!

I checked the directory. The folder Continuum is empty, I should re install anaconda?

**Comment by leti367** [comment] 2022-03-25 16:58
Yes, please reinstall it. Thanks!

> Hi Leti367!
> 
> I checked the directory. The folder Continuum is empty, I should re install anaconda?

**Comment by ayim** [comment] 2022-04-05 18:19
@leti367 is this more of an environment issue than an issue with our extension?

**Comment by leti367** [comment] 2022-04-05 18:27
@ayim, it's not an issue from our extension.

**Closed** 2022-04-05 18:31 UTC
Labels: product-issue, vscode, vscode-python

**Comment by FendaRoadz** [comment] 2022-04-09 11:02
Hi! I have this issue and cannot resolve it by myself. Please help. Thanx in advance! My intellicode output is

Language server is set to Pylance.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Language server extension command failed. Exception: Error: Connection got disposed.
	at Object.dispose (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:47:145778)
	at Object.dispose (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:155505)
	at S.handleConnectionClosed (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:155717)
	at S.handleConnectionClosed (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:32:10622)
	at t (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:153810)
	at invoke (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:281735)
	at o.fire (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:282496)
	at X (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:47:135140)
	at invoke (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:281735)
	at o.fire (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:282496)
	at d.fireClose (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:47:125209)
	at ChildProcess.<anonymous> (c:\Users\fenda\.vscode\extensions\ms-python.python-2022.4.1\out\client\extension.js:24:277465)
	at ChildProcess.emit (node:events:402:35)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Error while activating Python: {}
