### ISSUE TITLE
Sorry, something went wrong activating IntelliCode support for TypeScript/JavaScript

### ISSUE THREAD

**Issue by waiaan** [MicrosoftDocs/intellicode#545] opened 2024-03-14 07:58 UTC
**Product and Version** [VS/VSCode]: VSCode 1.87.2
**OS Version** [macOS/Windows]: Windows10 22H2 19045.4170
**IntelliCode Extension Version**:  1.3.0
**Target Platform or Language** [e.g. Node.js]: node 18.19.1

**Steps to Reproduce / Scenario:**

1. open js file with VSCode; 
2. it shows tip: 
    Sorry, something went wrong activating IntelliCode support for TypeScript/JavaScript. Please check the "VS IntelliCode" output window for details.
3. output window shows: 
   Acquiring model 'intellisense-members' for javascript
   Found bundled model for javascript
   Error while activating TypeScript/JavaScript: {}.

**Comment by oeyoews** [comment] 2024-03-14 08:58
It's very strange. 1.3.0 is a new version just released. The last update was a year ago. It's very strange.

**Comment by COOLIRON2311** [comment] 2024-03-14 11:48
Having the same issue

**Comment by Rrhapsod** [comment] 2024-03-14 12:36
Same problem here with 1.3.0 update

**Comment by oeyoews** [comment] 2024-03-14 13:07
Just roll back to the previous version for now

**Comment by MSK1206** [comment] 2024-03-14 15:28
### Disable Java input suggestions from IntelliCode settings in VsCode.

![2024-03-14 23-06-27-668](https://github.com/MicrosoftDocs/intellicode/assets/86665622/452f2f64-49a4-4fc7-be63-8e965313e4ac)

### Then restart VsCode.

**Comment by jcrasgado** [comment] 2024-03-14 15:46
Same issue 
Fedora 39 Kernel 6.7.9
IntelliCode 1.3.0

**Comment by MSK1206** [comment] 2024-03-14 16:11
バージョン: 1.87.2 (vscode)
Node.js: 18.17.1
OS: Windows 10 Pro

開いているエディターが残っていると、100％発生します。
VsCodeを終了するときは、すべてのエディターを閉じてからVscodeを閉じれば良さそうです。

**Comment by COOLIRON2311** [comment] 2024-03-14 16:42
> バージョン: 1.87.2 (vscode) Node.js: 18.17.1 OS: Windows 10 Pro
> 
> 開いているエディターが残っていると、100％発生します。 VsCodeを終了するときは、すべてのエディターを閉じてからVscodeを閉じれば良さそうです。

Confirmed. Even switching to another editor tab before closing VSCode temporarily resolves the issue.

**Comment by MSK1206** [comment] 2024-03-14 18:17
> > バージョン: 1.87.2 (vscode) Node.js: 18.17.1 OS: Windows 10 Pro
> > 開いているエディターが残っていると、100％発生します。 VsCodeを終了するときは、すべてのエディターを閉じてからVscodeを閉じれば良さそうです。
> 
> 肯定的。VSCodeを閉じる前に別のエディタタブ(javascriptやtypescriptなし)に切り替えても、問題は一時的に解決します。

I would also like to have a setting in setting.json that automatically closes all editors when VsCode is closed.💡

**Comment by geographerwang** [comment] 2024-03-15 00:40
anyone who has solved this problem?

**Comment by geographerwang** [comment] 2024-03-15 00:41
![image](https://github.com/MicrosoftDocs/intellicode/assets/12079968/d23fd256-623a-4827-b9db-822c424a1de0)

**Comment by oeyoews** [comment] 2024-03-15 00:42
install 1.2.x

**Comment by vivlimmsft** [comment] 2024-03-15 00:45
Sorry about that, we're investigating now.

**Comment by osobeso** [comment] 2024-03-15 00:57
This is a transient issue we are investigating.
It should go away if you restart VSCode or run Reload Window (Ctrl + Shift + P > Reload Window).

We will update the extension with a fix soon.

**Comment by waiaan** [comment] 2024-03-15 01:00
> This is a transient issue we are investigating. It should go away if you restart VSCode or run Reload Window (Ctrl + Shift + P > Reload Window).
> 
> We will update the extension with a fix soon.

thanks, but it did not work even after I restarted my computer.

**Comment by vivlimmsft** [comment] 2024-03-15 02:12
@osobeso and I investigated this together, we found the issue is that in some scenarios, the IntelliCode extension would activate before the built-in extension, `vscode.typescript-language-features`. We need that to already be active at the time IntelliCode is activating, to be able to add to it the plugin which adds stars to the completion list.

We were able to reproduce this 100% of the time by synthetically forcing IntelliCode to activate on non-JavaScript/TypeScript files (to guarantee `vscode.typescript-language-features` isn't running), and have a promising fix that we're testing now.

**Comment by osobeso** [comment] 2024-03-15 03:17
New version `1.3.1` has been released with a fix to the problem @vivlimmsft described above.

@waiaan thank you very much for reaching out and bringing this to our awareness.
Please let me know if the problem goes away for you so that I can close this issue.

Thanks!

**Comment by rexhang** [comment] 2024-03-15 05:50
v1.3.1 This bug has been fixed

<img width="503" alt="27b0219bc58e6d8ecebe91c6e3627aa" src="https://github.com/MicrosoftDocs/intellicode/assets/14832793/2c1d83ea-95fb-488e-9dfd-8b4679e48bb7">

**Comment by waiaan** [comment] 2024-03-15 05:53
> New version `1.3.1` has been released with a fix to the problem @vivlimmsft described above.
> 
> @waiaan thank you very much for reaching out and bringing this to our awareness. Please let me know if the problem goes away for you so that I can close this issue.
> 
> Thanks!

1.3.1 works fine now, thank you.

**Closed** 2024-03-15 07:17 UTC
Labels: vscode-intellicode, reliability
