### ISSUE TITLE
Fail to show intellisence when inputting optional parameters of methods on Python

### ISSUE THREAD

**Issue by AeneasZhu** [MicrosoftDocs/intellicode#96] opened 2019-05-12 00:43 UTC
t doesn't show any intellisense when I try to input the optional parameters in Python.

For instance, when I input 'RandomForestClassifier' and expect it can show the optional parameters like 'n_estimators', but it doesn't and shows nothing. It is sometimes very unconvenient especially when the optional parameters are long.

like this:
![image](https://user-images.githubusercontent.com/44701446/57576421-0fc31080-7492-11e9-94e3-b93fecff3ded.png)

By the way, when IntelliCode disabled and I just use the intellisense of the python extension, the optional parameters intellisence can work.

**Comment by jkeech** [comment] 2019-05-14 00:26
@AeneasZhu, this looks like a problem with the Microsoft Python Language Server (https://github.com/microsoft/python-language-server/issues/987) and not IntelliCode itself. You can confirm by disabling IntelliCode and keeping the Microsoft Python Language Server enabled by setting `"python.jediEnabled": false`.

**Comment by jkeech** [comment] 2019-05-14 22:19
Closing this issue, but please re-open if you believe this issue is directly caused by IntelliCode and is not related to the linked python language server issue. Thanks!

**Closed by jkeech** 2019-05-14 22:19 UTC
