### ISSUE TITLE
Annoying intellicode prompt appears on every window reload

### ISSUE THREAD

**Issue by connor4312** [MicrosoftDocs/intellicode#344] opened 2022-03-22 18:14 UTC
Issue Type: <b>Bug</b>

1. Open a python file
2. See an "interested in seeing API usage examples?" notification
3. Dismiss it
4. Reload and open a python file again
5. See the annoying notification again
6. Optional: disable the extension to stop the notification spam 😉 

The notification dismissal should be persisted.

Extension version: 1.2.17
VS Code version: Code - Insiders 1.66.0-insider (b0966eddca8cc86d3051213b6bf8327ef67ecf6d, 2022-03-22T07:31:08.410Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (39.52GB free)|
|Process Argv|--crash-reporter-id 08446e29-415a-41e0-84e3-0fb06040b4e4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vsclayoutctrt:30405800
dsvsc009:30440021
pythonvspyt640:30438691
vscscmwlcmc:30428972
vscgsvidc:30433759
pynewfile477:30451556

```

</details>

**Comment by markw-t** [comment] 2022-03-25 15:16
tagging @osobeso to take a look at this.

**Comment by osobeso** [comment] 2022-03-29 08:34
Hi @connor4312 
The state should be saved when you select the 'No Thanks' option, instead of dismissing.
The reasoning behind this mechanism, is that a 'dismissal' can be either user triggered (clicking the 'x') or time triggered (the user ignores the notification enough time for it to be hidden from view, this is usual on VsCode non-insiders).

Can you try selecting the 'No Thanks' option and seeing if that saves the state?

Also, you can disable this notification entirely by going into: File > Preferences > Settings > Extensions > Visual Studio IntelliCode

and set the following option as disabled: 
![image](https://user-images.githubusercontent.com/54292402/160568650-b00649a6-b741-4c23-a4c5-1d46ece0fbdb.png)

That should remove the problem for you.

Let me know if you need further assistance.
Thanks!

**Comment by connor4312** [comment] 2022-03-29 15:23
I suggest making "No Thanks" instead "Don't Show Again" to make this action explicit; that's what most of our notifications do, for example the devcontainer suggestion.

**Comment by osobeso** [comment] 2022-03-29 18:17
Thanks for the suggestion on the verbiage. I think we can add that change in the near future; I like it!
As for the persisted state, we do use local storage. The setting is an extra flag used to deactivate the promotion of the new extension (and also can be activated/deactivated by targeted notification when se to default).

**Comment by ayim** [comment] 2022-04-07 22:33
@osobeso wanted to check in on this:
1) was there a code change we needed to make/bug we needed to fix?
2) did we have a chance to make the language fix?

**Comment by osobeso** [comment] 2022-04-07 22:35
@ayim This will be fixed on our next release for VSCode, which will happen sometime around next week.

**Comment by ayim** [comment] 2022-04-25 18:38
Our fix should've gone out - @connor4312, appreciate you reporting this issue!

**Comment by ayim** [comment] 2022-05-11 00:24
<img width="561" alt="image" src="https://user-images.githubusercontent.com/10951869/167745136-f2c31f71-f3e5-410b-9209-2d0f43365316.png">
@osobeso looks like this is still occurring - mind taking a look?

**Comment by osobeso** [comment] 2022-05-11 00:34
Will take a look!

**Comment by osobeso** [comment] 2022-05-11 02:19
@ayim Created a PR to make the logic behind this less problematic. That will hopefully get rid of all the edge cases we've been experiencing.
I'll let you know once those changes are published on our Extension.

**Comment by dennorske** [comment] 2022-05-12 16:33
I can confirm it is still happening and has been for quite a while now. We're multiple people at work getting slightly annoyed over it, so wonderful if you can take a proper look at it 🙏 
Thanks for your help @osobeso! Looking forward to seeing it merged soon™️ 😊

**Comment by osobeso** [comment] 2022-05-12 21:53
@dennorske  this will be fixed with today's new release!
Just make sure to select the 'Don't show again Option' next time you see it.
Thanks!

**Comment by osobeso** [comment] 2022-05-12 23:24
@dennorske  the new version of the extension has been published!
Thanks for the feedback and the patience! 
Regards.

**Closed** 2022-08-05 06:49 UTC
Labels: product-issue, python-api-usage-examples
