### ISSUE TITLE
The IntelliSense suddenly not working for java

### ISSUE THREAD

**Issue by bobjiang1988** [MicrosoftDocs/intellicode#54] opened 2019-01-28 05:46 UTC
Here is the issue, Thank you.

https://github.com/redhat-developer/vscode-java/issues/779

**Comment by jkeech** [comment] 2019-01-28 17:03
Was it working previously? Based on the details in the other issue, it looks like your Java version is to low and is not supported. If you upgrade to 1.8.0_151 or higher it should work.

**Comment by NENightElves** [comment] 2019-01-29 12:10
@jkeech I got the same issue, you can see the detail in the link below:
https://github.com/redhat-developer/vscode-java/issues/779#issuecomment-458427251
Thank you!

**Comment by bobjiang1988** [comment] 2019-01-30 02:13
@jkeech I've upgraded the java version to 1.8.0_201 and nothing effect

**Comment by jkeech** [comment] 2019-01-30 03:57
Thanks for the latest details on the other issue. This is definitely a bug in the Java IntelliCode implementation. We are investigating the root cause and will reply back when we have a fix.

**Comment by akaroml** [comment] 2019-01-30 04:21
@Eskibear  could you please take a look?

**Comment by Eskibear** [comment] 2019-01-30 04:44
@bobjiang1988 
- For the original error log, it's due to the JDK version, and I think it has been resolved when as you've upgraded it to 8u201. (your latest log also indicates the activation has been completed)
- For the latest log you pasted in https://github.com/redhat-developer/vscode-java/issues/779#issuecomment-458791991 , I've gone through the code and indeed there's a potential NPE that can be caused by some corner cases we haven't cover yet. **I'll provide a fix for it.**

BTW, I think the completion should work well now except for some edge cases. Does the code completion break **all** or just **some** cases? Can you share a piece of code that can reproduce the NPE?

**Comment by bobjiang1988** [comment] 2019-01-31 01:41
@Eskibear

Maybe I didn't describe this issue clearly.

- I'm sure it worked very well even if my JDK version was 8u131. But I really don't known what I did to cause this issue.

- No effect after the upgrade except for the NPE . And it breaks all cases.

Code segment.

``` java
// Issue occurs if I don't import the PKG.
// import org.apache.commons.lang3.StringUtils;

public void intellisense(String cs) {
    StringUtils.isEmpty(cs); 
    // Bellow is what I want.
    // Input the first letter 'S', it could give me some suggestions of class or what ever starts with S.
}
```

**Comment by bobjiang1988** [comment] 2019-01-31 03:11
@Eskibear

You are totally right, VS Code doesn't send out the completion request.

Could you please help to check if it is conflict with **Spring Boot Tools**(Maybe the version of 4.1.1 RELEASE)? I disabled this extension and it starts working.

**Comment by Eskibear** [comment] 2019-01-31 03:32
Exactly. After disabling Spring Boot Tools v1.3.0, it works. 

And for VSCode 1.31.0-insider, the IntelliSense works well with the spring extension **enabled**.

**Comment by Eskibear** [comment] 2019-01-31 05:35
There's a same issue https://github.com/spring-projects/sts4/issues/193 . Since it's proved to be Spring Extension issue, I suggest we close this one and track it there. 

As for the unhandled NPE, i've already fixed it, should be shipped in next release of VSCode IntelliCode.

**Closed** 2019-01-31 05:56 UTC
