### ISSUE TITLE
C# ?

### ISSUE THREAD

**Issue by pedro15** [MicrosoftDocs/intellicode#280] opened 2021-03-25 16:43 UTC
When we can expect to get C# added to this plugin?

i mean the original intellicode has C# in visual studio 2019, why we can't get it on visual studio code?

**Comment by sonicbhoc** [comment] 2021-07-09 16:14
I have the same question.

**Comment by pixeldashgames** [comment] 2021-12-12 00:53
same question here

**Comment by markw-t** [comment] 2021-12-13 16:33
I believe this issue is a dupe of #81 in this repo. If folks agree I'll merge its votes into that item.

**Comment by tacosontitan** [comment] 2021-12-24 04:23
> I believe this issue is a dupe of #81 in this repo. If folks agree I'll merge its votes into that item.

Yes, it's a dupe.

**Comment by ayim** [comment] 2022-04-04 21:01
@markw-t, merging and closing.

**Closed by ayim** 2022-04-04 21:01 UTC
Labels: product-feedback, vscode, C#
