### ISSUE TITLE
Extension does not work on the latest VS Code Insiders

### ISSUE THREAD

**Issue by rzhao271** [MicrosoftDocs/intellicode#475] opened 2023-08-09 16:03 UTC
The latest VS Code Insiders is using Node v18.15.0
The extension seems to be making fetch calls with an "unknown scheme" and fails to load.

Extension output:

```
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:6768:35)
      at schemeFetch (node:internal/deps/undici/undici:10875:18)
      at node:internal/deps/undici/undici:10748:26
      at mainFetch (node:internal/deps/undici/undici:10765:11)
      at fetching (node:internal/deps/undici/undici:10722:7)
      at fetch2 (node:internal/deps/undici/undici:10600:20)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3623815
      at Object.<anonymous> (c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3624040) {
    [cause]: undefined
  }
}

Node.js v18.15.0
[Info  - 9:01:03 AM] Connection to server got closed. Server will restart.
[Error - 9:01:03 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:01:03 AM] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:6768:35)
      at schemeFetch (node:internal/deps/undici/undici:10875:18)
      at node:internal/deps/undici/undici:10748:26
      at mainFetch (node:internal/deps/undici/undici:10765:11)
      at fetching (node:internal/deps/undici/undici:10722:7)
      at fetch2 (node:internal/deps/undici/undici:10600:20)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3623815
      at Object.<anonymous> (c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3624040) {
    [cause]: undefined
  }
}

Node.js v18.15.0
[Info  - 9:01:10 AM] Connection to server got closed. Server will restart.
[Error - 9:01:10 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:01:10 AM] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:6768:35)
      at schemeFetch (node:internal/deps/undici/undici:10875:18)
      at node:internal/deps/undici/undici:10748:26
      at mainFetch (node:internal/deps/undici/undici:10765:11)
      at fetching (node:internal/deps/undici/undici:10722:7)
      at fetch2 (node:internal/deps/undici/undici:10600:20)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3623815
      at Object.<anonymous> (c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3624040) {
    [cause]: undefined
  }
}

Node.js v18.15.0
[Info  - 9:01:14 AM] Connection to server got closed. Server will restart.
[Error - 9:01:14 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:01:14 AM] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:01:14 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:6768:35)
      at schemeFetch (node:internal/deps/undici/undici:10875:18)
      at node:internal/deps/undici/undici:10748:26
      at mainFetch (node:internal/deps/undici/undici:10765:11)
      at fetching (node:internal/deps/undici/undici:10722:7)
      at fetch2 (node:internal/deps/undici/undici:10600:20)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3623815
      at Object.<anonymous> (c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3624040) {
    [cause]: undefined
  }
}

Node.js v18.15.0
[Info  - 9:01:19 AM] Connection to server got closed. Server will restart.
[Error - 9:01:19 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:01:19 AM] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:01:19 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: Error: unknown scheme
      at makeNetworkError (node:internal/deps/undici/undici:6768:35)
      at schemeFetch (node:internal/deps/undici/undici:10875:18)
      at node:internal/deps/undici/undici:10748:26
      at mainFetch (node:internal/deps/undici/undici:10765:11)
      at fetching (node:internal/deps/undici/undici:10722:7)
      at fetch2 (node:internal/deps/undici/undici:10600:20)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3623815
      at Object.<anonymous> (c:\Users\raymondzhao\.vscode-insiders\extensions\visualstudioexptteam.intellicode-api-usage-examples-0.2.7\dist\server\server.js:2:3624040) {
    [cause]: undefined
  }
}

Node.js v18.15.0
[Error - 9:01:21 AM] The API Usage Examples LSP server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 9:01:21 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:01:21 AM] API Usage Examples LSP client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 9:01:21 AM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

```

**Comment by drewbitt** [comment] 2023-08-09 21:13
I also get this.

**Comment by linuxdave** [comment] 2023-08-11 10:31
Getting this on v1.82.0-insider

**Comment by MohamedTharwat123** [comment] 2023-08-13 08:48
I also get this error

**Comment by recvmsgs** [comment] 2023-08-14 07:55
I've got this problem as well.

Version: 1.82.0-insider (user setup)
Commit: 76985ae7814f7cb28e2df6f1025d279bb77cbec1
Date: 2023-08-11T17:11:59.884Z
Electron: 25.4.0
ElectronBuildId: 22958381
Chromium: 114.0.5735.248
Node.js: 18.15.0
V8: 11.4.183.27-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by rzhao271** [comment] 2023-08-14 21:59
Node 18 comes with a `fetch` API, so the extension's use of `fetch` might be colliding with the new API.

**Comment by loktar00** [comment] 2023-08-18 17:08
Getting this as well on two separate machines.

**Comment by zapteryx** [comment] 2023-08-19 04:13
+1 on this as well

**Comment by rocketprogrammer** [comment] 2023-08-25 03:52
Getting this as well.

**Comment by k0r37k1** [comment] 2023-08-26 10:09
got the same bug with Nodejs v18 aswell when installed v20

**Comment by itsWeller** [comment] 2023-08-26 22:06
Experiencing the same crash with a similar stack trace, although the originating error is slightly different; `TypeError [ERR_INVALID_URL]: Invalid URL` vs. `Error: unknown scheme`.

```
TypeError: Failed to parse URL from /Users/cweller/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /Users/cweller/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3623815
      at Object.<anonymous> (/Users/cweller/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3624040)
      at 4087 (/Users/cweller/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/server.js:2:3657710) {
    input: '/Users/cweller/.vscode-insiders/extensions/visualstudioexptteam.intellicode-api-usage-examples-0.2.7/dist/server/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}
```

Aside from the extension itself not working, it also results in a flood of notifications spamming every new project window. 

<img width="465" alt="image" src="https://github.com/MicrosoftDocs/intellicode/assets/1703914/d1800c1a-579e-436d-bcd7-ecf42a55e607">

------

### Version info
#### Extension
- `visualstudioexptteam.intellicode-api-usage-examples` v0.2.7
#### VS Code
- Version: 1.82.0-insider (Universal)
- Commit: 501baeb5e07b5a404f862d922bacb93771d91331
- Date: 2023-08-18T05:34:38.929Z (1 wk ago)
- Electron: 25.5.0
- ElectronBuildId: 23084831
- Chromium: 114.0.5735.289
- Node.js: 18.15.0
- V8: 11.4.183.29-electron.0
- OS: Darwin x64 22.3.0 
#### OS
- macOS 13.2.1 (22D68) / Intel

**Comment by rocketprogrammer** [comment] 2023-09-03 00:56
Hopefully it's fixed soon

**Comment by sebmenard** [comment] 2023-11-02 22:08
I'm getting a similar issue with full line completions from both IntelliCode Completions and IntelliCode for C# Dev Kit (inline ones displayed with stars are working fine).

Example of output with the C# Dev Kit one:

```
[Completions][4]: [Child process] Unhandled rejection error: fetch failed
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Completions][4]: [Child process] Unhandled rejection error: fetch failed
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 0]  Caught error when requesting inline completion: Error: Operation took longer than 5000ms.
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 0] Unexpected exception: Operation took longer than 5000ms.
Error: Operation took longer than 5000ms.
	at Timeout._onTimeout (c:\Users\user\.vscode-insiders\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\dist\node_modules\@vsintellicode\completions-csharp\index.js:2:66913)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)
```

Going back to the latest VS Code version integrating Node 16 (v. 16.17.1) fixes the issue, which is version 1.81.1. Upgrading to the next version which is 1.82.3 triggers this issue as it integrates Node 18 (v. 18.15.0) since then.

This issue is still present in the latest version of VS Code (v. 1.84.0 as of now) and in the Insiders version (v. 1.85.0 as of now). Both are also using Node 18 (v. 18.15.0).

**Comment by timheuer** [comment] 2024-02-28 15:36
@sebmenard can you reopen the IntelliCode error as a separate issue to track.

**Comment by vivlimmsft** [comment] 2024-04-04 21:49
For the TS/JS/Python IntelliCode Completions extension, this was fixed with yesterday's update. (see #491)

For IntelliCode for C# Dev Kit, this will be fixed in an upcoming update. (see #535)

Closing this as a duplicate of those.

**Closed by vivlimmsft** 2024-04-04 21:49 UTC
Labels: bug, product-feedback, reliability, model-acquisition
