### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GIacobellis** [MicrosoftDocs/intellicode#63] opened 2019-02-28 14:45 UTC
- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.3`
- OS Version: `Windows_NT x64 10.0.15063`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `d:\Profiles\giacobellis\VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jkeech** [comment] 2019-02-28 17:55
Closing this as a duplicate of #60.

**Closed by jkeech** 2019-02-28 17:55 UTC
