### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Classy-Bear69** [MicrosoftDocs/intellicode#68] opened 2019-03-07 16:05 UTC
- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.3`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/myUser/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jkeech** [comment] 2019-03-07 17:00
Thanks for the report! Closing as a duplicate of #60. This should be fixed soon with version 1.1.4 of the extension.

**Closed by jkeech** 2019-03-07 17:00 UTC
Labels: duplicate
