### ISSUE TITLE
Intellicode Completions - fetch failed

### ISSUE THREAD

**Issue by Useroth** [MicrosoftDocs/intellicode#542] opened 2024-02-08 18:17 UTC
**Product and Version** [VS/VSCode]: 1.86.1
**OS Version** [macOS/Windows]: Windows 10
**IntelliCode Extension Version**:  Intellicode Completions v1.0.22
**Target Platform or Language** [e.g. Node.js]: Python (probably more)

**Steps to Reproduce / Scenario:**

1. Install "Intellicode Completions" extensions.
2. Try to get completions in a python file.
3. Get the following in the extension console output: 
![image](https://github.com/MicrosoftDocs/intellicode/assets/37159550/d508d814-3750-44d3-ba04-e8febcfad735)

```
Extension version: 1.0.22 034a5c7
[Worker thread] Unhandled rejection error: fetch failed
[Worker thread] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Worker thread] Unhandled rejection error: fetch failed
[Worker thread] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by vivlimmsft** [comment] 2024-03-15 20:12
Duplicate of #491

**Closed by vivlimmsft** 2024-03-15 20:12 UTC
Labels: bug, vscode-completions
