### ISSUE TITLE
Not support ".mjs" file(node.js 14)

### ISSUE THREAD

**Issue by flier268** [MicrosoftDocs/intellicode#241] opened 2020-10-26 06:23 UTC
Node.js 14 will be LTS, but intellicode still not support .mjs file.

**Product and Version** :1.50.1
**OS Version** :Windows
**IntelliCode Extension Version**: 1.2.10
**Target Platform or Language** :Node.js 14

**Comment by catycaldwell** [comment] 2020-10-26 15:54
@uniqueiniquity @minestarks  is this something that you all can take a look ?

**Comment by uniqueiniquity** [comment] 2020-10-26 16:23
Hello @flier268!

Using VS Code 1.50.1 and the IntelliCode extension 1.2.10, I am able to get IntelliCode results in a .mjs file.

![mjsIntelliCode](https://user-images.githubusercontent.com/9092011/97199037-ca210300-176c-11eb-81e6-1f6160a967c8.gif)

Could you please share more concrete steps to reproduce the issue you are observing?

Thank you!

**Comment by flier268** [comment] 2020-10-26 16:40
### a1.mjs
```javascript
export default class a1{
    constructor(){

    }
    functionA(){
        
    }
}
```
### a2.mjs
```javascript
import a1 from './a1.mjs'
new a1()
```
![圖片](https://user-images.githubusercontent.com/19989232/97201031-ebc1cf00-17ec-11eb-9439-5f20f4341d7a.png)

**Comment by uniqueiniquity** [comment] 2020-10-26 16:51
@flier268, 

Thank you for the additional information!
This seems to be an issue with TypeScript's support for `.mjs` imports, rather than IntelliCode's.
Please file this issue, including the repro you provided, at https://github.com/microsoft/typescript and they'll best be able to help you.

**Comment by DavidObando** [comment] 2020-10-26 17:33
Thank you @flier268 for the report. Indeed this looks like this isn't IntelliCode as @uniqueiniquity mentioned. We'll go ahead and close this issue, but it appears you were affected by this: microsoft/typescript#27957

**Closed** 2020-10-26 17:32 UTC
Labels: JS/TS, javascript, vscode

**Comment by flier268** [comment] 2020-10-27 02:20
Thanks for @uniqueiniquity , @DavidObando  and @catycaldwell help.
