### ISSUE TITLE
Suggestions not popping up

### ISSUE THREAD

**Issue by borekb** [MicrosoftDocs/intellicode#23] opened 2018-12-06 09:02 UTC
**VS Code Version**: 1.29.1
**OS Version** [macOS/Windows]: macOS
**Visual Studio IntelliCode Extension Version**: 1.1.0
**Target Platform or Language** [e.g. Python]: TypeScript

I'm not getting any IntelliCode suggestions in VSCode stable (1.29) at this point, while I do get them in Insiders (1.30). Are there known compatibility issues with other extensions? Or is this intended to work in Insiders only for now?

I'm seeing this in the output panel in 1.29, all seems fine:

```
Acquiring model 'JSIntelliCode-Completions'  with schema version between [1, 1]
Querying IntelliCode service for available models.
Endpoint: https://ppe.intellicode.vsengsaas.visualstudio.com/api/v2/repoAgnostic/analyzers/JSIntelliCode/models/latest?declaredName=Completions&minSchemaVersion=1&maxSchemaVersion=1
Downloading model.
Starting download of https://cdsmppestg.blob.core.windows.net/codesmartsfileshares-ppe/completions-181002173250434-1?sv=2017-04-17&sig=%2Br1SnwTUx0LfwFzjJlEx0cFK4i6dn2VVIWC3wYvZzU0%3D&spr=https&se=2018-12-07T08%3A49%3A46Z&srt=o&ss=b&sp=rl
Download complete.
```

I just don't get any "★" suggestions:

![image](https://user-images.githubusercontent.com/101152/49573283-ee3b8700-f93d-11e8-8a89-8201b81e49d1.png)

**Comment by svipben** [comment] 2018-12-06 12:47
Try to run 2 VS Code instances, one with the existing project for e.g. your personal one or company which uses JS or TS. And another one empty (just click `CMD + SHIFT + N`). In both of them open a new Untitled file and set language mode to JavaScript. Does both doesn't show AI based suggestions? Try to do this on Stable VS Code (1.29.1).

I'm asking this because for me this issue occurs: https://github.com/MicrosoftDocs/intellicode/issues/22. It doesn't work on existing project, but if I open a new one it works fine.

**Comment by borekb** [comment] 2018-12-06 12:51
@svipben it behaves exactly like you described.

Interestingly, in 1.30, all works fine, be it a new or an existing project.

**Comment by svipben** [comment] 2018-12-06 12:53
I also found that in Insiders it works better, but didn't try to do the same with Insiders (as mentioned above). Thanks for testing it out!

Good news is a new version of VS Code will be released soon so for now I guess we need to wait :)

**Comment by jkeech** [comment] 2018-12-06 17:32
IntelliCode is expected to work correctly in both 1.29 and 1.30, although there are some improvements coming in 1.30 which will make the experience a bit better. @minestarks, can you take a look?

**Comment by minestarks** [comment] 2018-12-06 20:51
Thanks @borekb for the report, I'll look into it. Can I close this as a duplicate of #22 ?

**Comment by minestarks** [comment] 2018-12-06 20:54
Also, if you could attach a tsserver log ("TypeScript: Open TS Server Log" from the command palette) that would be really helpful for me to root cause.

**Comment by borekb** [comment] 2018-12-06 21:09
Hi @minestarks, could you email me at `borekb@gmail.com` please? I'd reply with the log attached. It contains some paths that I'm not comfortable posting publicly.

What I can say now is that I've tried on another repo and there, all works fine. What is different with my problematic repo is that it's quite a large one – uses the monorepo pattern with many different TypeScript / JavaScript projects at once. TS Language Server usually doesn't have a problem with that but maybe the IntelliCode extension does.

**Comment by minestarks** [comment] 2018-12-06 22:52
We root caused this to the fact that the IntelliCode plugin doesn't load when using a TypeScript version from the workspace instead of VS Code's own version. 

You can work around this for now by choosing to use TypeScript from VS Code and not the workspace:

![image](https://user-images.githubusercontent.com/16928427/49616694-89485700-f966-11e8-9ec8-96c254dbe2e8.png)

**Comment by minestarks** [comment] 2018-12-07 21:12
Closing in favor of #32 with more specific description.

**Closed by minestarks** 2018-12-07 21:12 UTC

**Comment by DanJ210** [comment] 2019-01-08 21:23
@minestarks If I'm not using TypeScript but instead JavaScript and I'm not getting AI suggestions, does that count for this thread? I've created a new window and a blank new JS file but I'm still not getting any starred suggestions. Just the normal thing I've always seen.
