### ISSUE TITLE
VSCode JavaDoc Code Completion is not showing

### ISSUE THREAD

**Issue by ahmedhamdy2121** [MicrosoftDocs/intellicode#263] opened 2021-01-05 22:39 UTC
VSCode JavaDoc Code Completion is not showing for Java code; If you write the first some letters of a function, then pressed control + space (or it will be shown automatically), you expect to see code completion with documentation per function, but what is happening is that the code completion is the only one shown, do documentation at all.

However, if I hover over a function, the JavaDoc is shown correctly, so I have JavaDoc correctly configured, and this is clearly a bug in code completion with Java.

**Product and Version** [VS/VSCode]: 1.52.1
**OS Version** [macOS/Windows]: macOS 10.15.7 Catalina
**IntelliCode Extension Version**: Java Extension Pack (0.12.1) & Language Support for Java (0.73.0)
**Target Platform or Language** [e.g. Node.js]: Java

**Steps to Reproduce / Scenario:**

1. Open any Java class.
2. Type "Math."

Code Completion will be shown but without the JavaDoc!

Please check the below GIF
![VSCode Bug](https://user-images.githubusercontent.com/252999/103707322-01cdd780-4f74-11eb-96cb-e9a3b5f4c8d1.gif)

**Comment by markw-t** [comment] 2021-01-11 19:52
Hi @ahmedhamdy90 , 

Thanks for raising this problem. It looks like IntelliCode itself is working as normal but there is a problem with the Java support in VS Code. Tagging @Eskibear  to take a look and confirm next steps.

Thanks
mark

**Comment by Eskibear** [comment] 2021-01-12 02:40
I can reproduce it. Let me take a look.

**Comment by Eskibear** [comment] 2021-01-12 03:33
Found the culprit: there's a bug when converting completion items between LSP format and Code format.

I'll send out a PR later. It will look like below then:

![image](https://user-images.githubusercontent.com/2351748/104265984-b1053400-54c9-11eb-8ebf-dd528301bdb8.png)

**Comment by markw-t** [comment] 2021-01-12 16:28
Thank you for investigating and finding the root cause @Eskibear! Once the PR is out can you advise how @ahmedhamdy90 can pick up the updated bits? Will he be auto-updated if he has the Java extension for VS Code installed?

**Comment by Eskibear** [comment] 2021-01-13 02:50
The PR is for Java part of IntelliCode-VSCode, and the fix will be shipped with IntelliCode.

**Comment by TFrascaroli** [comment] 2021-01-27 09:15
Is there an ETA for the fix to be included in an update? I'm on Linux, if that makes any difference.

**Comment by markw-t** [comment] 2021-01-27 15:57
I'll let @Eskibear comment on timelines for release in an update.

**Comment by Eskibear** [comment] 2021-01-28 01:48
The patch has been merged. IntelliCode Core team is in charge of the release. I'm requesting a new release to ship the fix, and I'll let you know if there's any progress or response.

**Comment by theGirrafish** [comment] 2021-07-04 15:02
@Eskibear Do you know the current status for this bug? I'm currently on VSCode 1.57.1 and IntelliCode 1.2.14 and still having this issue. This ticket has been open for over 6 months now, is it still only waiting on a release?

**Comment by Eskibear** [comment] 2021-07-05 01:48
@theGirrafish It was released with IntelliCode 1.2.12 several months ago.

> I'm currently on VSCode 1.57.1 and IntelliCode 1.2.14 and still having this issue.

I cannot reproduce it on my machine. Can you provide more details? e.g.
* enable/disable IntelliCode extension, see if it's the same behavior?
* what's the version of extension "Language Support for Java by Red Hat"?
* Is your JDK correctly configured and what's your project type?
* ...

**Comment by theGirrafish** [comment] 2021-07-05 19:04
@Eskibear After looking more into it, it only seems to be a problem when I have my maven project set to use Java 8, while my `java.home` path is set to use Java 11 (this is because the Java by Red Hat extension requires Java 11+ for language support).
When I change my maven project to use Java 11, the documentation works as expected.

I'm using:

- Language Support for Java by Red Hat version 0.80.0
- Maven with Java version 8
- VSCode `java.home` pointing to Java 11 JDK

**Comment by Eskibear** [comment] 2021-07-06 08:28
I'm also using JDK 11 to launch Red Hat Java extension, and JDK 8 for my Maven project. And everything works fine.

> enable/disable IntelliCode extension, see if it's the same behavior?

Please give it a try. Let's first figure out which extension is wrong. If the issue is still there no matter whether IntelliCode is enabled or not, you should open a ticket here 
 https://github.com/redhat-developer/vscode-java/issues . 

And if possible please provide a sample project (because I cannot reproduce it with a simple maven project).

**Comment by ayim** [comment] 2022-02-16 02:43
hey hey @theGirrafish! Just wanted to make sure this is working for you - are you seeing any further issues?

**Comment by ayim** [comment] 2022-03-28 19:03
Gotcha - I'm going to close this for now, but feel free to reopen if you're finding issues with it in the future!

**Closed by ayim** 2022-03-28 19:03 UTC
Labels: product-issue, java
