### ISSUE TITLE
Models downloaded to working directory (non-absolute path)

### ISSUE THREAD

**Issue by jakebailey** [MicrosoftDocs/intellicode#231] opened 2020-09-30 17:57 UTC
I can't transfer issues here, so here is a re-report of microsoft/pylance-release#331.

The model the IC extension is downloading and providing to Pylance appears to be done non-absolutely, leaving random model files downloaded to whatever the working directory is.

```json
[{"analyzerName":"intellisense-members-lstm-pylance","languageName":"python","identity":{"modelId":"E61945A9A512ED5E1A3EE3F1A2365B88F8FE","outputId":"E4E9EADA96734F01970E616FAB2FAC19","modifiedTimeUtc":"2020-08-11T14:06:50.811Z"},"filePath":"E61945A9A512ED5E1A3EE3F1A2365B88F8FE_E4E9EADA96734F01970E616FAB2FAC19","lastAccessTimeUtc":"2020-09-03T00:47:30.529Z"}]
```

Note the non-absolute `filePath`. The user in the linked issue sees these files redownloaded depending on how they opened their editor.

Pylance only consumes these files, it doesn't produce them (and it extracts the files to a specific location as needed).

**Comment by osobeso** [comment] 2020-10-03 05:55
Thanks for opening this issue @jakebailey 
I will take a look at it.
It does seem weird, I haven't seen this happening before, and we haven't changed the code on that model download logic in a while.

I will take a look to try and get to the root cause.
Regards,
Oscar.

**Comment by highpost** [comment] 2020-10-08 07:04
I reported the original issue. My VSC environment is pretty generic: only a few extensions and they're mostly popular ones. But I do build my own Python executable from source and then create a venv.

**Comment by osobeso** [comment] 2020-10-14 03:15
@highpost Hi there!

There's a small hack you can do to fix this issue locally.
Go to File>Preferences>Settings and search for "model download path".
You can modify this variable to have a personalized absolute path. This will make sure that all models are always managed on that directory and that directory only.

You will need to modify the settings using the settings.json file, this is the structure of that property:
"vsintellicode.modelDownloadPath": "",

The reason I'm telling you to fix it this way, is because after doing some investigation, the root cause seems to be a transient issue on VSCode's context argument we use to locate the Extension folder (instead of us having to browse trough the hard drive to find it, since it differs from installation to installation).

So right now there's nothing we can do on our side to fix that problem, but overriding that value should be enough for you to not experience this problem anymore.
Let me know if you have any other questions, and thanks for the feedback!

Oscar.

**Comment by ayim** [comment] 2023-06-16 03:08
Closing since there's nothing we can do on our end - workaround available above.

**Closed by ayim** 2023-06-16 03:08 UTC
Labels: product-issue, python, vscode

**Comment by vivlimmsft** [comment] 2024-03-15 20:19
As of v1.3.0 we don't download models anymore, they're part of the extension. So this shouldn't be possible anymore. Unpinning.
