### ISSUE TITLE
Intellicode for C# Dev Kit Not Working

### ISSUE THREAD

**Issue by Number-3434** [MicrosoftDocs/intellicode#535] opened 2024-01-16 17:41 UTC
Intellicode does not work if the solution is inside a folder in the workspace.

**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1. Make sure VSCode is on the latest version.
2. Install the C# Dev Kit extension.
3. Make sure all extensions are on the latest version.
4. Install the Unity extension if necessary.
5. Create a new Unity project, and open VSCode two folders up in the hierarchy from the project, and create a new C# script.

Type anything. There are no completions.

Looking at the output, it seems the given score for the completions are negative.

**Comment by AaronBeaudoin** [comment] 2024-01-19 14:19
I am also experiencing this issue.

Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

Here is my output after typing a few characters in a `.cs` file:

```
Inline Completions document change subscription registered.
Initializing IntelliCode Inline Completions
[Completions][2]: Completions worker with process id 30780 has been created
Inline Completions Initialized
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 0]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 0] Skipping request
[Completions][2]: [CompletionState.getLineCompletion()] : Best suffix
	First token score log confidence: 0 < -0.35667494393873245
	Suggestion: 
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 0]  Candidate completion: 
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 0]  Current line with candidate:

[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 0]  Completion was filtered out because Completion line is an empty string
[Completions][2]: [Child process] Worker with pid 30780 has started
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][4]: [Child process] Unhandled rejection error: fetch failed
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Completions][4]: [Child process] Unhandled rejection error: fetch failed
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 1]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 1] Starting request
[Completions][1]: [WorkerLineCompletionService.request() 2]  Entered
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 1]  Recieved cancellation event, ran for 560.2026000022888
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 2]  Entered provideInlineCompletionItems() try block
[Completions][1]: [inlineCompletionProvider.provideInlineCompletionItems() 2] Starting request
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 1]  Caught error when requesting inline completion: Error: Operation took longer than 5000ms.
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 1] 
	Wait: 0.3776000738143921ms
	Full inference: 5002.360299944878
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 1] Unexpected exception: Operation took longer than 5000ms.
Error: Operation took longer than 5000ms.
	at Timeout._onTimeout (c:\Users\AaronBeaudoin\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\dist\node_modules\@vsintellicode\completions-csharp\index.js:2:66913)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)
[Completions][1]: [WorkerLineCompletionService.request() 3]  Entered
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 2]  Caught error when requesting inline completion: Error: Operation took longer than 5000ms.
[Completions][2]: [inlineCompletionProvider.provideInlineCompletionItems() 2] 
	Wait: 4273.758199930191ms
	Full inference: 5001.661500096321
[Completions][4]: [inlineCompletionProvider.provideInlineCompletionItems() 2] Unexpected exception: Operation took longer than 5000ms.
Error: Operation took longer than 5000ms.
	at Timeout._onTimeout (c:\Users\AaronBeaudoin\.vscode\extensions\ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64\dist\node_modules\@vsintellicode\completions-csharp\index.js:2:66913)
	at listOnTimeout (node:internal/timers:569:17)
	at process.processTimers (node:internal/timers:512:7)
```

**Comment by Number-3434** [comment] 2024-01-19 14:42
Yeah, <samp>First token score log confidence: 0 < -0.35667494393873245</samp> seems a bit worrying

**Comment by DanStevens** [comment] 2024-01-23 10:28
I thought I was having this problem, but then I realised that the C# solutions I was working on was in a sub-directory within the currently opened workspace. It appears the C# Dev Kit isn't clever enough to work with multiple solutions in a workspace. I Opened the solution directory directly and now Intellicode is working for me.

**Comment by Number-3434** [comment] 2024-01-23 12:32
Ahh yes, that would make sense.

I think I remember having it work at some point, and I think I was directly in the directory at that point. Thanks!

**Comment by JasonKroll** [comment] 2024-01-25 05:44
> I thought I was having this problem, but then I realised that the C# solution I was working on was in a sub-directory within the currently opened workspace. It appears the C# Dev Kit isn't clever enough to work with multiple solutions in a workspace. I Opened the solution directory directly and now Intellicode is working for me.

This has not made any difference to me unfortunately.

**Comment by Number-3434** [comment] 2024-01-25 07:03
> This has not made any difference to me unfortunately.
Yeah, I just tried this, and my score is still negative.

**Comment by AlexandreBossard** [comment] 2024-03-08 11:17
Intellicode for C# is still completely broken with vscode 1.87. Is there a solution or alternative somewhere ? This is unacceptable to be broken for so long.

**Comment by ViA8604** [comment] 2024-03-15 05:53
> Intellicode for C# is still completely broken with vscode 1.87. Is there a solution or alternative somewhere ? This is unacceptable to be broken for so long.

Just wanted to complain too. I'm so tired of having problems with C# snippets in vscode. Recently the extensions updated(I'm going to disable that next time for sure) and then snippets stopped working. I'll try with installing the new vscode version, but yep, the 1.87.0 it's the one I've got.

**Comment by navarone77** [comment] 2024-03-26 23:16
yup still broken.. Tried reverting back to no avail.

**Comment by ViA8604** [comment] 2024-03-27 12:22
Hey, I can use C# snippets now. I reinstalled Code and just installed C# extension, without Intellicode or anything else. Maybe the other extra related extensions are causing the problem. Hope it helps.

**Comment by AlexandreBossard** [comment] 2024-04-03 11:21
Any news? Still not working for me. This extension is directly linked and recommended in the microsoft/vs-code documentation. Being broken for so long is baffling!

**Comment by vivlimmsft** [comment] 2024-04-04 01:30
There's an extension update coming within the next few days that should fix the issue where the extension doesn't work on VSCode >= 1.82.

This should restore the two features that IntelliCode implements:
- When you have a completion list, it may include suggested items prefixed with a ⭐
- Inline completions (gray text which appears in your document while you are typing, that you can accept with `Tab`)

If you are seeing problems other than that (e.g. *no* completion lists at all), then the issue is likely in the main C# Dev Kit extension *unless* uninstalling IntelliCode resolves the issue. So if you continue to see problems after the update, check if uninstalling IntelliCode makes a difference.

*BTW, the scores printed in the log are supposed to be negative, they're the logarithm of values < 1. The printed confidence threshold is *before* log is applied, `log(0.39)` is `-0.4089`. The next update improves (some) of the output logging around this.*

**Comment by Bowman74** [comment] 2024-04-05 00:15
@vivlimmsft 

That's great to hear. I am currently creating a LinkedIn learning class that shows this exact extension. I hate it when I have to explain that something doesn't currently work. I will be recording next month so hopefully this is fixed before then.

**Comment by vivlimmsft** [comment] 2024-04-05 00:38
I've queued up the release, there's still a chance I could hit an unforeseen problem (the publishing pipeline has not been fully exercised since ... July) but if all goes well the release should roll out tomorrow morning PDT.

If not, then it'll be later that day, or if something went *really* wrong, next week.

**Comment by Bowman74** [comment] 2024-04-05 15:15
@vivlimmsft 
Thank you. When I get the new version I will report back to you on the results.

One more question if you know. For the version in Visual Studio it will work for line completion without an internet connection. I'm under the impression from the documentation and discussions that the version for VS Code only works when the user is online. Is this assumption correct? (I want to make sure I don't spread bad information).

**Comment by vivlimmsft** [comment] 2024-04-05 21:02
v2.0.25 was published to the marketplace earlier today, which should fix this issue. Please open a new issue if you see any problems after updating. Closing this as resolved.

@Bowman74, the VSCode version of line completions should also work without an internet connection. If any of our docs are saying otherwise, or if anyone's observing that line completions stop working without internet, that's a bug.

**Closed by vivlimmsft** 2024-04-05 21:02 UTC
Labels: vscode-cdk, reliability

**Comment by Bowman74** [comment] 2024-04-05 23:51
@vivlimmsft 
I have tried out the new version and indeed IntelliCode line completion is working again. It doesn't seem to work quite as well as it does in Visual Studio, but that may simply because I haven't been working with it in Visual Studio Code long enough to get the same level of context built.

Now that it works again I also confirmed that it does indeed work offline. Nowhere in the documentation does it say that IntelliCode for Visual Studio Code doesn't work offline. It was more that the documentation for Visual Studio IntelliCode explicitly stated that full line auto completion works offline:

https://learn.microsoft.com/en-us/visualstudio/ide/intellicode-privacy?view=vs-2022

The Visual Studio Code documentation didn't mention it one way or another which made me suspect that wasn't a feature. Since the extension didn't work I had no way to know for sure.

https://code.visualstudio.com/docs/csharp/intellicode

**Comment by KjongSounnd** [comment] 2025-03-08 01:41
> Intellicode จะไม่ทำงาน หากโซลูชันอยู่ภายในโฟลเดอร์ในเวิร์กสเปซ
> 
> **ผลิตภัณฑ์และเวอร์ชัน** [VS/VSCode]: **เวอร์ชันระบบปฏิบัติการ** [macOS/Windows]: **เวอร์ชันส่วนขยาย IntelliCode** : **แพลตฟอร์มหรือภาษาเป้าหมาย** [เช่น Node.js]:
> 
> **ขั้นตอนในการทำซ้ำ / สถานการณ์:**
> 
> 1. ตรวจสอบให้แน่ใจว่า VSCode เป็นเวอร์ชันล่าสุด
> 2. ติดตั้งส่วนขยาย C# Dev Kit
> 3. ตรวจสอบให้แน่ใจว่าส่วนขยายทั้งหมดเป็นเวอร์ชันล่าสุด
> 4. ติดตั้งส่วนขยาย Unity หากจำเป็น
> 5. สร้างโครงการ Unity ใหม่ และเปิด VSCode สองโฟลเดอร์ขึ้นไปในลำดับชั้นจากโครงการ และสร้างสคริปต์ C# ใหม่
> 
> พิมพ์อะไรก็ได้ ไม่มีคำเติมเต็ม
> 
> เมื่อดูที่เอาต์พุต ดูเหมือนว่าคะแนนที่กำหนดไว้สำหรับการดำเนินการให้สำเร็จจะเป็นค่าลบ

**Comment by KjongSounnd** [comment] 2025-03-21 20:06
> Intellicode does not work if the solution is inside a folder in the workspace.
> 
> **Product and Version** [VS/VSCode]: **OS Version** [macOS/Windows]: **IntelliCode Extension Version**: **Target Platform or Language** [e.g. Node.js]:
> 
> **Steps to Reproduce / Scenario: **
> 
> 1. Make sure VSCode is on the latest version.
> 2. Install the C# Dev Kit extension.
> 3. Make sure all extensions are on the latest version.
> 4. Install the Unity extension if necessary.
> 5. Create a new Unity project, and open VSCode two folders up in the hierarchy from the project, and create a new C# script.
> 
> Type anything. There are no completions.
> 
> Looking at the output, it seems the given score for the completions are negative.
