### ISSUE TITLE
[VS] VB.NET support

### ISSUE THREAD

**Issue by yalexopoulosQ** [MicrosoftDocs/intellicode#34] opened 2018-12-07 20:30 UTC
**Product and Version** [VS/VSCode]:
**OS Version** [macOS/Windows]:
**IntelliCode Extension Version**: 
**Target Platform or Language** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by Nukepayload2** [comment] 2018-12-08 08:51
I think adding VB.NET support is easier than adding C++. Because VB can use the API usage telemetry data of C#. For example, if people usually write `if(string.IsNullOrEmpty(str))` in C#, when you are typing `If String.` in VB, IntelliCode should suggest `IsNullOrEmpty` in the VB editor.

**Comment by popasUC** [comment] 2018-12-17 15:51
Please add support for VB.Net in IntelliCode at the same level as C#.
Surely the lack of it cannot be for technical reasons, rather "political".

Why so little love for VB.Net in the past over 5 years?
Despite the cold shoulder from Microsoft, VB.Net is still at least as popular as C# (the latest TIOBE index shows it's still 2 X more popular than C#). Not only cold shoulder, but outright peer pressure (smells like bullying) where many (even prominent) VB.Net developers were scared into the "**_VB.Net is obsolete. You MUST use C# if you want to stay current_**" trend.  

Are the Microsoft teams responsible for language evolution serving the interest of the Developer community or just the interests of {;} "professionals" who feel threatened by a more normal and natural language syntax? Well, now Python is taking over in popularity and, ironically, it has many of the VB.Net traits.

VB.Net makes programming so easy and natural, it had the potential to become the "Python" of .Net.
With a little bit more fair treatment from Microsoft (cannot ask for love where there is none) VB.Net could have made the top 3 by language popularity.

I chose the Microsoft platform over 30 years ago because they delivered on their mission statement to **make software simple to use and easily accessible** most of the time, with VB, Windows, SQL Server etc. 
I hope Microsoft will continue on that path and keep VB.Net at par with C#.

**Comment by tom1417** [comment] 2019-02-12 22:57
I would absolutely agree that VB.Net should be included into intellicode. VB as stated above has such broad applications to newer developers whereas c# can be intimidating to those who are not traditionally trained. Not only that, I personally prefer the natural expression that VB permits. Market VB as the Microsoft analog to Python instead of leaving it at the bottom of the list!

**Comment by Timgy1959** [comment] 2019-03-14 12:06
I agree - I use VB.Net out of choice and prefer to use it to show beginners how programming works. Being an older programmer I have experience in how daft some language centric developers can be.  Asking them to try resorting to writing the same in Assembler (as I had to for the much needed speed back then) usually shut them up.

**Comment by Spoelle** [comment] 2019-03-14 15:53
Same here: include VB.Net please !

**Comment by moellnator** [comment] 2019-03-15 15:42
VB.NET is my first choice for programming as well. As a scientist I always need a fast and reliable way of developing and testing algorithms, hardware control, data analysis, etc. VB.NET in conjunction with the Visual Studio makes rapid prototyping so simple, that I just need to think about the task not the code. This workflow would obviously benifit from IntelliCode for VB.NET. So, I also request the implementation.

**Comment by bdcoder2** [comment] 2019-03-17 01:33
Alright - I'll be blunt - I think VB is a great language. Nearly every program / website / utility I have written is in VB.Net -- I started using BASIC over 40 years ago -- and still prefer it today (and yes, I do know how to code using at least 12 other programming languages).

However, it seems (recently) that VB.Net is being treated as a second class citizen by MS -- did anyone notice that only C# examples are present in the latest .Net features / documentation set?  What happened to the VB.Net examples that used to be included?

ANY and ALL features available in C# should also be available in VB.Net (within language constraints of course).

Would it help if we rename VB.Net to B# so it sorts higher on the MS development list?

Either keep B# in step with C#, or just come out and say you will be dropping support for VB.Net by YYYY-MM-DD, to give us a big head start in porting code.  

Thank-you for your consideration (and reading my rant)!  :)

**Comment by AndreaLazz** [comment] 2019-04-09 10:27
I agree with bdcoder2, VB.NET and C# should have the same features.

**Comment by Vicharian** [comment] 2019-04-16 21:45
+1

**Comment by filippobottega** [comment] 2019-04-18 15:45
+1000 😉

**Comment by OlafBr** [comment] 2019-04-26 15:54
+ 2^64

**Comment by InteXX** [comment] 2019-05-06 23:07
@bdcoder2 

In the musical world, B# is C  ;-)

Yes, Microsoft, please give VB.NET the attention it deserves and longs for. After all, you wouldn't be where you are today without it.

**Comment by JensSamsonPirsol** [comment] 2019-05-24 06:55
The silence is deafening.

**Comment by bdcoder2** [comment] 2019-05-24 14:40
Yes – too bad – In my opinion, Microsoft is missing one of the biggest opportunities in programming history…

Consider, there exists a growing list of programming languages that all use a DIFFERENT syntax for the SAME functions.  For example, loops, declaring variables, comparison operators, standard data types and objects – WHY do we need so many different syntaxes for these basic (excuse the pun) constructs?

Granted – ALL programming languages have their unique abilities – but they also have common denominators (loops, variables, data types, comparison operators as described above).

Hold on to your keyboards -- Just image for a moment -- a SINGLE language / syntax for loops, variables, data types and comparison operators.  There are just too many advantages to list if a common syntax was available for 90% of the common constructs that all languages contain.   This is not a unique idea – someone proposed it a while back, see: [https://theuknownprogrammer.blogspot.com/2017/07/40-years-of-programming.html](https://theuknownprogrammer.blogspot.com/2017/07/40-years-of-programming.html)

If a single programming language was proposed, then let the developer community VOTE on the syntax for these common language constructs.  If nothing else, it would be a very interesting project; one that could benefit our (programming) community for decades.   The military learned this back in the 1970’s – when they moved to a single programming language (Ada) to replace an unmanageable number of languages. 

So, a common syntax for the common programming constructs; marry this with libraries that can use these common data types and objects -- such as the .Net Framework, or .Net core – good grief, what a world THAT could be!

[End of rant - again]

**Comment by NLWaard** [comment] 2019-06-06 20:22
+1
Why do we have to ask for this?
Please include VB.Net in intellicode !

**Comment by basti01985** [comment] 2019-06-07 08:10
+1
Please support Intellicode in VB.NET

**Comment by Andreas2015** [comment] 2019-06-19 11:45
+1
The world is moving, I know. 
One of the advantages of .NET is the diversity of languages. And I personally have a strong curly braces allergy, where VB.NET helps to restore my health after Java / JavaScript / C# jobs.

**Comment by jkeech** [comment] 2019-07-12 19:30
Thanks everyone for the feedback so far. I'm excited to share that we are working on adding VB support for IntelliCode in Visual Studio. Stay tuned for more details!

**Comment by InteXX** [comment] 2019-07-12 19:32
@jkeech 

Wonderful! Thank you, John  :-)

**Comment by bdcoder2** [comment] 2019-07-12 22:04
BASICally, the best news I have heard in a long time ...

Would it be possible to get the following addressed as well (to bring us back in line with C#)?
[Formatting / spacing options for Basic ...](https://developercommunity.visualstudio.com/content/problem/331415/where-are-the-formatting-spacing-options-for-vb.html)

Thanks in advance !

**Comment by jkeech** [comment] 2019-07-12 23:40
@bdcoder2, the VB formatting options are maintained by a different team separate from IntelliCode. The Developer Community problem you referenced is the right place to follow up on that issue. I see that the problem is reported as fixed on May 28, although I don't see options myself. You might want to comment on that problem if it isn't fixed for you. Thanks!

**Comment by bdcoder2** [comment] 2019-07-13 00:39
@jkeech - Got it - thanks!! Yes - reported fixed on May 28, then my post was actually read and was changed to "under consideration"on Sep 17, 2018...

I was hoping maybe an inter-departmental memo from one team to the other might have some weight / merit !   In the interim, I'll ask the other team (again) if the formatting options can be brought up to par with C#

Cheers

**Comment by CavitDraman** [comment] 2019-07-30 06:44
+10000

**Comment by abuchholtzau** [comment] 2019-09-03 22:59
We're pleased to announce that we've added VB support to IntelliCode in Visual Studio 2019 Update 3 Preview 2 (aka 16.3 Preview 2) 😀
As this is still a Preview feature for IntelliCode, you'll need to enable it by switching to Tools > Options > IntelliCode > Visual Basic base model to Enabled.

We look forward to your feedback and hope this model delights you!

**Closed by abuchholtzau** 2019-09-03 22:59 UTC
Labels: enhancement

**Comment by narslankaya** [comment] 2020-08-04 08:12
+1
Please support Intellicode in VB.NET

**Comment by arisbouras** [comment] 2020-08-18 14:26
Does anyone know if and when there will be vb.net Intellicode for VSCode (Visual Studio CODE) ?
Thank you in advance

**Comment by markw-t** [comment] 2020-08-18 15:30
As noted above, we support IntelliCode completions for VB.NET on Visual Studio 2019 Update 3 (aka 16.3) and higher.

However we don't have any current plans to support IntelliCode features for VB.NET (or C#) on Visual Studio Code.

I see you've opened a new issue to track this (#219 )  @arisbouras ; thanks! Folks can upvote that issue and indicate their support for this feature there. (#81 is tracking the suggestion for VS Code support for C#).

Thanks
Mark

**Comment by ranasrule** [comment] 2024-04-28 14:27
Please add support for VB.Net in IntelliCode at the same level as C#.

**Comment by InteXX** [comment] 2024-04-28 21:54
@bdcoder2 

*"Would it help if we rename VB.Net to B# so it sorts higher on the MS development list?"*

FYI you've been nominated for the Quote of the Year:

https://discord.com/channels/682603493386747904/1073635946567835798

**Comment by ShaggyTheHiker** [comment] 2024-06-09 18:04
This has not gotten enough notice, which will keep the votes somewhat suppressed. It would be an excellent improvement.

**Comment by Nukepayload2** [comment] 2024-06-10 01:42
If Microsoft won't align IntelliCode of VB.Net to the same level as C#, we can implement it by ourselves. I'm recently trying to use LlamaSharp and the DeepSeek-Coder/Llama3 LLM to implement similar features of Copilot. It can run locally if you have a NVIDIA GPU with 12GB+ VRAM and compute capability >= 8.0. DeepSeek-Coder is used for filling-in-the-middle (FIM). Llama3 is used to handle other tasks. The prototype has been implemented. An AvaloniaEdit control can do VB code completion without attaching to Roslyn. It can also answer questions based on the selected source files. I'm currently finding suitable data sets to PEFT the LLMs to insert EOS tokens at appropriate position and avoid explaining the code outside of the comment syntax nodes.

**Comment by InteXX** [comment] 2024-06-10 04:51
@Nukepayload2 

I like your attitude.

This sounds like something the VB.NET community can use. I encourage you to discuss it in our small Discord group, at https://discord.com/channels/682603493386747904/.

You might also find ModVB by Anthony Green—former VB.NET team lead—of interest (discussed there as well). Still in early pre-alpha stage, it promises to enable us to make our own Roslyn-compatible modifications to VB.NET and publish them for community consumption. It's his answer to Microsoft's abandonment of our favorite programming language.
