### ISSUE TITLE
A JNI error has occurred

### ISSUE THREAD

**Issue by Ayush-bhargav** [MicrosoftDocs/intellicode#222] opened 2020-08-26 05:38 UTC
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: ghhmgm has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by Ayush-bhargav** [comment] 2020-08-26 05:38
help me to run java on my vs code

**Comment by Eskibear** [comment] 2020-08-27 01:55
It's not related to completion, probably caused by inconsistent JDK versions on your machine.
See https://github.com/microsoft/vscode-java-debug/issues/859 for more help.

**Comment by markw-t** [comment] 2020-08-27 22:46
Closing based on @Eskibear's comment above. Please refer to the issue he linked. If it doesn't help, please let us know.

In addition, you can find general guidance on setting up VS Code to use Java [here](https://code.visualstudio.com/docs/java/java-tutorial)

**Closed by markw-t** 2020-08-27 22:46 UTC
Labels: java, product-issue
