### ISSUE TITLE
How to disable model download and use model cache directly?

### ISSUE THREAD

**Issue by birdhackor** [MicrosoftDocs/intellicode#525] opened 2023-11-21 03:36 UTC
The development environment of my company cannot access the external network, so I manually downloaded the model and placed it in the development environment.

But every time I open VSCode, intellicode will try to connect to the IntelliCode service to confirm whether there is a new model. IntelliCode will not operate normally until TIMEOUT.

How can I turn off the latest model check, or reduce the length of TIMEOUT?

#102

**Comment by vivlimmsft** [comment] 2024-04-04 21:20
Last month we [released v1.3.0 to the marketplace](https://marketplace.visualstudio.com/items?itemName=VisualStudioExptTeam.vscodeintellicode) which no longer downloads models from a service, they are all included in the extension package now. (duplicate of #102)

**Closed by vivlimmsft** 2024-04-04 21:20 UTC
Labels: product-feedback, model-acquisition
