### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dbryantm** [MicrosoftDocs/intellicode#67] opened 2019-03-07 04:48 UTC
Hi, I'm not sure that I'm submitting this issue correctly, but hopefully I am. It just seems like intellicode was having high CPU load and VS Code sent me here so I figured I should go ahead and submit it. Thanks!

- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.3`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

Here's the file that was requested to be included:

[VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt](https://github.com/MicrosoftDocs/intellicode/files/2939554/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt)

**Comment by jkeech** [comment] 2019-03-07 16:59
Thanks for the report! Closing as a duplicate of #60. This should be fixed soon with version 1.1.4 of the extension.

**Closed by jkeech** 2019-03-07 16:59 UTC
