### ISSUE TITLE
something went wrong activating IntelliCode support for Python.

### ISSUE THREAD

**Issue by unique1o1** [MicrosoftDocs/intellicode#57] opened 2019-01-31 15:45 UTC
**Product and Version** [VS/VSCode]: VSCode
**OS Version** [macOS/Windows]: Linux
**IntelliCode Extension Version**:  1.1.2

**Target Platform or Language** [e.g. Node.js]: Python

**Steps to Reproduce / Scenario:**

1. Open vscode
2. Wait for extensions to load

Experiencing problem with Visual Studio intellicode extension with following error on start:
> Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.

**Comment by markw-t** [comment] 2019-02-01 17:09
@unique1o1 I'm glad that all is working correctly now; seems like it was a transient problem so it's hard to speculate on root cause. 

Since you are no longer seeing the issue, I'm going to close it out, but if it re-occurs please don't hesitate to send along the VS IntelliCode and Python window info so we can look into it further.

**Comment by markw-t** [comment] 2019-02-01 17:11
If others are seeing this issue - please pass on your VS IntelliCode & Python output window traces so we can investigate. Thanks!

**Comment by vivlimmsft** [comment] 2019-02-04 18:40
Thanks for the log. I'll reopen this issue.

**Comment by jwilkins88** [comment] 2019-02-08 22:44
Same problem over here. 

**Python output:**

```
Starting Microsoft Python language server.
Microsoft Python Language Server version 0.1.78.0
Initializing for /home/joelw/.local/share/virtualenvs/external-api-XMKiMtIU/bin/python
##########Linting Output - pylint##########
##########Linting Output - pylint##########

------------------------------------
Your code has been rated at 10.00/10
```

**Intellicode output:**

```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"/home/joelw/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.3/IntellicodeModels/88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {"name":"Error","message":"command 'python._loadLanguageServerExtension' not found"}
```

Intellicode version 1.1.3

**Comment by jkeech** [comment] 2019-02-08 22:50
Thanks @jwilkins88 and @davidpodrebarac! I think there's a race condition in the activation of both the IntelliCode and Python language server extensions. Even if the Python extension is loaded, the language server that the extension spins up might not be fully initialized yet. So if the Python extension loads, then the IntelliCode extension, then the Python language server initializes, we will hit this issue.

We are adding some code to ensure the IntelliCode extension waits for the Python language server to fully initialize in all cases instead of relying on just the extension to be activated. This should be fixed in the next release. In the mean time, if you hit this issue, then reloading VS Code should fix the problem.

**Comment by taosx** [comment] 2019-02-10 18:01
Found the same issue:

**Python output:**

```
Starting Microsoft Python language server.
##########Linting Output - mypy##########
##########Linting Output - pylint##########
************* Module admin.items
1,0,convention,missing-docstring:Missing module docstring
11,0,convention,missing-docstring:Missing class docstring
17,0,convention,missing-docstring:Missing class docstring
47,0,convention,missing-docstring:Missing class docstring

------------------------------------------------------------------
Your code has been rated at 9.02/10 (previous run: 9.02/10, +0.00)
```
**Intellicode output:**

```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"/home/assosx/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.3/IntellicodeModels/88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {"name":"Error","message":"command 'python._loadLanguageServerExtension' not found"}
```
Intellicode version 1.1.3

**Comment by Dafeesh** [comment] 2019-02-12 21:55
Same issue:
**Python output:**
```
Starting Microsoft Python language server.
##########Linting Output - pylint##########
Microsoft Python Language Server version 0.1.78.0
Initializing for /usr/local/bin/python3
```
**VS Intellicode output:**
```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"/Users/blakesch/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.3/IntellicodeModels/88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {"name":"Error","message":"command 'python._loadLanguageServerExtension' not found"}
```

And something funny is going on with Jupyter, not sure if related?
```
Unable to determine version of Jupyter, Error: spawn jupyter ENOENT
```

**Comment by hochae** [comment] 2019-02-13 04:08
In my case, it was working to reload VS Intellicode pack following the reinstall the Python extension pack.

**Comment by jkeech** [comment] 2019-02-14 20:45
A fix has been made for this issue and will be released in our next update (1.1.4).

**Comment by jkeech** [comment] 2019-03-07 19:46
Version 1.1.4 has been published to the marketplace. Please update and let us know if you continue to see this problem. Thanks!

**Closed by jkeech** 2019-03-07 19:46 UTC
Labels: bug

**Comment by wmpeng** [comment] 2019-04-24 05:36
Same issue to me, and I got two different outputs:
```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"c:\\Users\\wmpen\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.1.5\\IntellicodeModels\\88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {}
```
and

```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Couldn't reach service Error Message: connect ETIMEDOUT 137.135.104.11:443, (Error)
Could not reach the IntelliCode service. Checking the local model cache.
Recent model was found in cache.
vs-intellicode-python was passed a model: {"modelPath":"c:\\Users\\wmpen\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.1.5\\IntellicodeModels\\88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {}
```

It may seem to be related to the network?

**Comment by takaragi17** [comment] 2019-04-24 06:01
@wmpeng 
Faced same issue. That is caused by Microsoft/vscode-python#5437
Try downgrading the version of "Python" extension as mentioned by comments on above issue.

**Comment by trobr** [comment] 2019-04-24 06:10
Same issue too:
```
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"c:\\Users\\br\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.1.5\\IntellicodeModels\\88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {}
```

**Comment by wmpeng** [comment] 2019-04-24 06:17
> @wmpeng
> Faced same issue. That is caused by [Microsoft/vscode-python#5437](https://github.com/Microsoft/vscode-python/issues/5437)
> Try downgrading the version of "Python" extension as mentioned by comments on above issue.

It works for me.

**Comment by Tympani** [comment] 2019-04-24 11:56
The same issue
And still not work after I downgraded the version of "Python"
`Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"/Users/hankinzhang/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.5/IntellicodeModels/88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {}
`

**Comment by takaragi17** [comment] 2019-04-24 12:11
@Tympani 
Did you disable automatic update extensions? If not, disable it and try downgrading again.

**Comment by wenh06** [comment] 2019-04-24 12:51
> @Tympani
> Did you disable automatic update extensions? If not, disable it and try downgrading again.

I can't find a place to download an older version of the python extension.

**Comment by cdfmlr** [comment] 2019-04-24 13:09
> > @Tympani
> > Did you disable automatic update extensions? If not, disable it and try downgrading again.
> 
> I can't find a place to download an older version of the python extension.
> I found it...Install another version...

The same issue, too.
How did you solve it? I'm still puzzled. could you please offer any detail?

**Comment by mecaxis14** [comment] 2019-04-24 13:45
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Cached model is up to date.
vs-intellicode-python was passed a model: {"modelPath":"c:\\Users\\Administrador.WIN-I8N98UV2N9N\\.vscode\\extensions\\visualstudioexptteam.vscodeintellicode-1.1.5\\IntellicodeModels\\88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {}

**Comment by rafaelefucho** [comment] 2019-04-24 14:31
Acquiring model 'intellisense-members' for python
Querying IntelliCode service for available models.
Downloading model.
Starting download of https://cdsmprodstg.blob.core.windows.net/models-prod-output/Output_88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C?sv=2018-03-28&sr=b&sig=B%2Bj7Y8oijuTf%2BKkZB2dQyrrFoP0fgdv0gx7DlI8hkLc%3D&se=2019-04-24T14%3A59%3A43Z&sp=r
Download complete.
vs-intellicode-python was passed a model: {"modelPath":"/home/administrateur/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.1.4/IntellicodeModels/88630A1B4C077752096ECAA576B92C7D3FA1_AFE724E3F06E46849C99F748E987227C","modelId":"88630A1B4C077752096ECAA576B92C7D3FA1","outputId":"AFE724E3F06E46849C99F748E987227C"}.
Error while activating Python: {}

**Comment by wmpeng** [comment] 2019-04-24 15:08
> > > @Tympani
> > > Did you disable automatic update extensions? If not, disable it and try downgrading again.
> > 
> > 
> > I can't find a place to download an older version of the python extension.
> > I found it...Install another version...
> 
> The same issue, too.
> How did you solve it? I'm still puzzled. could you please offer any detail?

If you are using vscode, you can do like this:

![批注 2019-04-24 230527](https://user-images.githubusercontent.com/17960972/56670565-a5664e00-66e5-11e9-9950-6db0a6fa8401.png)
![批注 2019-04-24 230804](https://user-images.githubusercontent.com/17960972/56670661-d8a8dd00-66e5-11e9-89a1-464d1e4aa589.png)

**Comment by cdfmlr** [comment] 2019-04-24 15:42
> > > > @Tympani
> > > > Did you disable automatic update extensions? If not, disable it and try downgrading again.
> > > 
> > > 
> > > I can't find a place to download an older version of the python extension.
> > > I found it...Install another version...
> > 
> > 
> > The same issue, too.
> > How did you solve it? I'm still puzzled. could you please offer any detail?
> 
> If you are using vscode, you can do like this:
> 
> ![批注 2019-04-24 230527](https://user-images.githubusercontent.com/17960972/56670565-a5664e00-66e5-11e9-9950-6db0a6fa8401.png)
> ![批注 2019-04-24 230804](https://user-images.githubusercontent.com/17960972/56670661-d8a8dd00-66e5-11e9-89a1-464d1e4aa589.png)

Thank you. It's do useful. I have solved my problems now.
By the way, I tried to *remove last extra comma from "~/.vscode/extensions/ms-python.python-2019.4.11881/package.nls.[language].json."* according to [Microsoft/vscode-python#5437](https://github.com/Microsoft/vscode-python/issues/5437), it's also useful.

**Comment by jkeech** [comment] 2019-04-24 16:50
Just to confirm, this is an issue with the Python extension that was recently updated (Microsoft/vscode-python#5437). The Python extension owners are rolling out a fix, but in the mean time, you can work around it by installing an older version of the Python extension temporarily. The IntelliCode activation error for python files is side-effect from the Python extension failing to load.

**Comment by takaragi17** [comment] 2019-04-25 00:39
Now fixed version (2019.4.11987) of Python extension has been released. Downgrading or manual fixing is no longer needed. Updating Python extension should resolve this issue.

**Comment by debuggerpk** [comment] 2019-04-30 08:32
still not resolved for me, have upgraded to latest.

**Comment by jkeech** [comment] 2019-04-30 16:34
@debuggerpk, can you open a new issue with more details? It's likely a different problem. Thanks!

**Comment by EralpCelebi** [comment] 2021-03-18 07:21
I am having the same issue right now:/

**Comment by devanghingu** [comment] 2021-05-12 12:29
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.
i m facing same issue right now after update.

**Comment by markw-t** [comment] 2021-05-12 15:56
@devanghingu, @EralpCelebi sorry to hear this. It would help to see the contents of your Python and VS IntelliCode output windows as this will often give clues as to what is going on.  Can you open a new issue with that information please? /cc @savannahostrowski  @luabud

**Comment by devanghingu** [comment] 2021-05-13 10:41
@markw-t  i updated with new issue Please check #290

**Comment by Dampop1** [comment] 2022-05-10 12:26
Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: command 'python.viewOutput' already exists."}}

**Comment by omidshojaee** [comment] 2022-08-25 14:59
I have this issue right now.

VSCode : 
```
Version: 1.71.0-insider
Commit: 7ed02a69658fc07f08740b98fa0d8d96c1a61ed4
Date: 2022-08-24T05:18:46.886Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```
Python extension: v2022.13.12371004
VS IntelliCode extension: v1.2.23

Python output window:
```
ERROR 2022-7-25 19:20:25.864]: sendStartupTelemetry() failed. Error: Can not delete in empty document
    at R (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:19:2203)
    at D.getEdits (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:9718)
    at D.updateConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8952)
    at D.doWriteConfiguration (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8556)
    at async Object.factory (vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2696:8216)
```

VS IntelliCode  output:

```
Language server is set to "Default". Pylance is used as current language server.
Acquiring model
Acquiring model 'intellisense-members-lstm-pylance' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Activating Python extension
Error while activating Python: {"name":"Error","message":"Can not delete in empty document"}
```

**Comment by Krish2649** [comment] 2022-08-29 13:34
same issue

Output:

`Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: Cannot find module 'c:\\Users\\Lenovo\\.vscode\\extensions\\ms-python.python-2022.12.1\\out\\client\\extension'\nRequire stack:\n- c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\vs\\loader.js\n- c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\bootstrap-amd.js\n- c:\\Users\\Lenovo\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\bootstrap-fork.js."}}`

**Comment by Jagdish2022** [comment] 2022-09-11 10:31
I have the same issue:

Output:

VS Intellicode:
  Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: command 
  'python.viewOutput' already exists."}}

Python:
  Starting Jedi Python language engine.
  ##########Linting Output - pylint##########

**Comment by jessutanto** [comment] 2022-11-29 08:54
I have the same issue

Output
Python:
[ERROR 2022-10-29 9:47:52.455]: extension activation failed [Error: command 'python.viewOutput' already exists
	at s.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:92:109710)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:32839)
	at s.registerCommand (/Users/jessutanto/.vscode/extensions/ms-python.python-2022.18.2/out/client/extension.js:2:109254)
	at /Users/jessutanto/.vscode/extensions/ms-python.python-2022.18.2/out/client/extension.js:2:397997
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async t.activateComponents (/Users/jessutanto/.vscode/extensions/ms-python.python-2022.18.2/out/client/extension.js:2:396775)
	at async /Users/jessutanto/.vscode/extensions/ms-python.python-2022.18.2/out/client/extension.js:2:2182448
	at async e (/Users/jessutanto/.vscode/extensions/ms-python.python-2022.18.2/out/client/extension.js:2:2181998)
	at async w._activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:8304)
	at async w._waitForDepsThenActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:8246)
	at async w._initialize (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:90:7610)]

VS IntelliCode:
Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: command 'python.viewOutput' already exists."}}

**Comment by spignelon** [comment] 2023-10-28 11:10
I am still having the same issue and switching it to pre-release version didn't fix it either.

"Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details."
![image](https://github.com/MicrosoftDocs/intellicode/assets/92091338/d029fabb-c026-4463-b650-0fc9cbdc2efc)

![image](https://github.com/MicrosoftDocs/intellicode/assets/92091338/8fe35a8f-7295-4b63-9fd1-8305414410d2)

The solution written in the issue: https://github.com/microsoft/vscode-python/issues/18109 doesn't work either:
https://github.com/microsoft/vscode-python/issues/18109#issuecomment-985733678

**Comment by CXK-Computer** [comment] 2024-08-15 15:14
Fuck

**Comment by issam-seghir** [comment] 2024-09-09 11:02
Going to the Python extension in the store (ms-python.python), then update the extension or switch to (pre-release) and restart VSCode fix the problem for me

**Comment by absognety** [comment] 2024-09-17 07:33
> Going to the Python extension in the store (ms-python.python), then update the extension or switch to (pre-release) and restart VSCode fix the problem for me

Yes this fixed the problem for me too, and I have tried everything before that including restarting vscode, commenting out deprecated settings from `.vscode` folder of workspace.
