### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by DragonFZJ** [MicrosoftDocs/intellicode#66] opened 2019-03-06 12:47 UTC
- Issue Type: `Performance`
- Extension Name: `vscodeintellicode`
- Extension Version: `1.1.3`
- OS Version: `Linux x64 4.15.0-29deepin-generic`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/dragonf/VisualStudioExptTeam.vscodeintellicode-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by jkeech** [comment] 2019-03-06 16:56
Thanks for the report! Closing as a duplicate of #60. This should be fixed soon with version 1.1.4 of the extension.

**Closed by jkeech** 2019-03-06 16:56 UTC
