### ISSUE TITLE
Intellicode not getting activated for python. ( Error while activating Python: {} )

### ISSUE THREAD

**Issue by Dharaneeshwar** [MicrosoftDocs/intellicode#223] opened 2020-08-28 18:27 UTC
**Product and Version** [VS/VSCode]: VSCode
**OS Version** [macOS/Windows]: Windows 10
**IntelliCode Extension Version**:  1.2.10
**Target Platform or Language** [e.g. Node.js]: Python

**Steps to Reproduce / Scenario:**

1. Open Vscode
2. Wait for the extension to load for a python file

Getting this notification at first 
```
Sorry, something went wrong activating IntelliCode support for Python. Please check the "Python" and "VS IntelliCode" output windows for details.
```
Output window of VSIntellicode shows this. 

```
Language server is set to Microsoft.
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Error while activating Python: {}
```

I currently have no idea how to fix this issue.

**Comment by Dharaneeshwar** [comment] 2020-08-29 06:44
Closed this because Intellicode started working after multiple reinstalls.

**Comment by markw-t** [comment] 2020-08-31 15:28
Thank you for letting us know, and sorry that you had to re-install to get this working. Do let us know if you experience problems again or have other feedback.

Regards
Mark

**Comment by nik-ahuja** [comment] 2020-10-30 04:16
Hey @markw-t  any idea on this bug, I have tried multiple reinstalls didn't work for me.

**Comment by markw-t** [comment] 2020-10-30 15:22
tagging @osobeso on @nik-ahuja 's question above.

**Comment by nik-ahuja** [comment] 2020-11-02 01:29
Hey, @markw-t @osobeso the issue is resolved for me, turns out the extensions can't use environment variables for proxy. Specifying the proxy settings in VS Code resolved the issue. Although I think there should be a fix for that, is it already planned?

**Comment by osobeso** [comment] 2020-11-03 00:31
Hi @nik-ahuja 
This seems to be related to VS Code itself, and its way of handling proxy inside VS Code's environment.
We don't have anything planned in the near future to override this behavior on our side. We usually point to the proxy settings on VS Code for this kind of proxy configuration issues. Good to know that you found the setting and were able to fix it!

I'll let you know if I find out that there are upcoming changes for this on the VS Code platform.

Thanks again for the feedback, and thank you for using IntelliCode!

Oscar.

**Comment by nik-ahuja** [comment] 2020-11-03 05:24
Thanks @osobeso  VS Code itself can access system env proxy variables but for some reasons Intellicode can't get that setting from VS Code. I am sure this was not the case earlier, maybe something changed in the recent updates from VS Code.

**Comment by osobeso** [comment] 2020-11-03 16:45
@nik-ahuja oh, I understand now, thanks for the observation.

I took a look at our codebase and it seems we do have a VsCode library that we haven't updated in a while (seems like all http request calls get tunneled trough these libraries, so the proxy settings are handled  automatically in there).

I'm not 100% sure if this is the root cause though, so I will investigate that and try and schedule an update as soon as possible.
I will close this bug and create a new more specific issue targeting the issue of IntelliCode extension not using the Environment Variables for proxy as default.

Thanks again!

**Closed by osobeso** 2020-11-03 16:45 UTC
Labels: vscode-python
