### ISSUE TITLE
VS IntelliCode Model Download fails

### ISSUE THREAD

**Issue by samoretc** [MicrosoftDocs/intellicode#134] opened 2019-10-10 22:03 UTC
Model download fails. This bug was first reported by @sanket-bhalerao [here](https://github.com/microsoft/vscode/issues/82230).

![66557061-eb697e00-eb6e-11e9-895d-c7344ef0ea19](https://user-images.githubusercontent.com/5169473/66609939-1fdd3a00-eb6f-11e9-8ca3-d9cf51aec5de.png)

Issue Type: Bug

vs intellicode download fails.
issue started appearing after upgrade to version 1.40.0 (insiders)
along with the vs intellicode issue, java language server and java extensions are also failing to start/work

VS Code version: Code - Insiders 1.40.0-insider (193fead, 2019-10-10T05:26:43.233Z)
OS version: Windows_NT x64 10.0.17134
Remote OS version: Linux x64 4.15.0-64-generic

**Comment by sanket-bhalerao** [comment] 2019-10-11 09:28
this issue is appearing when i am connecting to remote using Microsoft remote extensions.
if this helps in tracing the issue.

**Comment by sanket-bhalerao** [comment] 2019-10-14 07:56
observations:
1. The issue can be reproduced when used with vscode remote and insiders build.
2. The issue does not appear in stable build + vscode remote.

**Comment by sanket-bhalerao** [comment] 2019-10-15 05:28
hi,
the issue is fixed appears to be fixed with the latest vscode insiders update. I don't see any update on intellicode extension. so assuming the issue was caused by earlier updates of VSCode insiders.


Version: 1.40.0-insider (user setup)
Commit: 3d3202804b4644f58cfac014e39b77dd36a6d226
Date: 2019-10-14T21:15:27.586Z
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

![image](https://user-images.githubusercontent.com/9264813/66802624-b2e4ee00-ef3a-11e9-82e5-7b29def98782.png)

**Closed** 2019-10-30 17:49 UTC
