### ISSUE TITLE
Method brackets don't auto open&close after using the extension

### ISSUE THREAD

**Issue by aleksastojsic** [MicrosoftDocs/intellicode#269] opened 2021-01-19 12:23 UTC
The extension works great. The only downside for me as a beginner is that when I'm using the extension the brackets for methods, for example, `response.json()` do not automatically close. When I disable the extension they are opening/closing just fine.

**Product and Version**: Visual Studio Code 1.52.1
**OS Version**: Windows 10 Pro
**IntelliCode Extension Version**: v1.2.10
**Target Platform or Language**: JavaScript
**Steps to Reproduce / Scenario:**

1. Type `response.jso` , then when the recommendation comes up press enter you should get `response.json` (without ())
2. Type `response.jso` , with extension disabled, then when the recommendation comes up press enter you should get `response.json()`

`e.preventDefault();`  same thing, brackets don't get typed, I have to type them myself.

This is my first issue report, so my bad for the bad formatting, hopefully, you get the point.

**Comment by minestarks** [comment] 2021-01-19 17:02
Hi @aleksa-stojsic , from your description I'm assuming the "Complete Function Calls" `javascript.suggest.completeFunctionCalls` setting is enabled in VS Code. Could you confirm?

I couldn't reproduce the issue easily - auto-completing braces works for me regardless of IntelliCode is enabled or not.

Is it possible for you to share a whole file / project that demonstrates this behavior?

**Comment by aleksa-stojsic** [comment] 2021-01-19 18:29
I checked and I have Complete Function Calls set to true `"javascript.suggest.completeFunctionCalls": true` in my settings.

Where could I share the files? I tried pasting the code here with `` but it gets all messy. This is my first issue request on GitHub so it might also be that I'm just bad.

**Comment by minestarks** [comment] 2021-01-19 18:56
@aleksa-stojsic  no worries, GitHub actually makes it kind of tricky. To paste large snippets of code you can surround it with ``` (three backticks). Alternatively, if you're sharing a whole project with multiple files, some people just create a new repo on GitHub with their sample code and share a link to it.

**Comment by aleksa-stojsic** [comment] 2021-01-19 20:04
[Here is the link to those 2 files](https://github.com/aleksa-stojsic/javascript-ninja/tree/master/weather_app/scripts) where I used the methods mentioned above and was not getting the brackets. Thanks for the help and tips @minestarks !

**Comment by minestarks** [comment] 2021-01-19 20:38
Thanks! Using that repo, I can repro your issue now. We'll investigate as soon as we can!

**Comment by minestarks** [comment] 2021-01-26 18:14
Investigation notes: This behavior is coming from the TypeScript IntelliCode plugin.

Comparing the good/bad logs shows that we're marking the element as a "property", whereas VS Code expects "method" to add the function call braces.

From the tsserver logs...

IntelliCode off:
`{"name":"json","kind":"method","kindModifiers":"declare","sortText":"0"}`

IntelliCode on:
`{"name":"★ json","kind":"property","sortText":"*a 0","insertText":"json"}`

I'm not sure at the moment what the fix should be.

**Comment by aleksa-stojsic** [comment] 2021-05-06 12:39
Update on this issue. I think you are right @minestarks, I've noticed that properties don't get self-closing brackets ```()``` when I type enter in VSCode, or even ```(``` instead of Enter. I'll have to do some testings on the new machine with Ubuntu subsystem on my laptop. While I'm lerning, typing some new projects, I can post the updates on this issue here if that helps. Testing things with IntelliCode Extension on/off and ```javascript.suggest.completeFunctionCalls``` to true/false etc.

**Closed** 2022-09-26 23:24 UTC
Labels: product-issue, vscode, javascript
