### ISSUE TITLE
Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: command 'python.viewOutput' already exists."}}

### ISSUE THREAD

**Issue by Jagdish2022** [MicrosoftDocs/intellicode#405] opened 2022-09-11 10:13 UTC
Error while activating Python: {"detail":{"name":"Error","message":"Activating extension 'ms-python.python' failed: command 'python.viewOutput' already exists."}}

**Comment by markw-t** [comment] 2022-09-12 18:43
Looks like a duplicate of #404

**Closed by markw-t** 2022-09-12 18:43 UTC
