### ISSUE TITLE
PLEASE HELP!!! NEED SOLUTION TO THIS HUGE PROBLEM OF INTELLICODE COMPLETIONS!!!

### ISSUE THREAD

**Issue by Musulmankul05** [MicrosoftDocs/intellicode#514] opened 2023-10-29 09:34 UTC
[Worker thread] Unhandled rejection error: fetch failed
[Worker thread] Unhandled rejection error stack: TypeError: fetch failed
     at Object.fetch (node:internal/deps/undici/undici:11413:11)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Worker thread] Unhandled rejection error: fetch failed 
[Worker thread] Unhandled rejection error stack: TypeError: fetch failed
     at Object.fetch (node:internal/deps/undici/undici:11413:11)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
Extension version: 1.0.22 034a5c7

**1.83.1** [VS/VSCode]:
**Windows 11 22H2** [macOS/Windows]:
**1.0.22 034a5c7**: 
**Python 3.11** [e.g. Node.js]:

**Steps to Reproduce / Scenario:**

1.
2.

**Comment by PiemP** [comment] 2023-10-31 07:18
Is the same here. Intellicode for C# Dev Kit crash with almost the same error: 

```
[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][4]: [Child process] Unhandled rejection error: fetch failed
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Completions][4]: [Child process] Unhandled rejection error: fetch failed
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by tvgulik** [comment] 2023-11-17 09:42
We have got the same problem. Code completion just completaly fails in visual studio code with our (large) webassembly blazor project. Visual studio does not have these problems with the same project. In smaller projects code completion works fine. I suspect that the issue has to do some thing with size and it gets a timeout

[Completions][2]: [Child process] Requested setting state for intellicode-completions.internal.defaultConfidenceThreshold = 0.39 (default is 0.39)
[Completions][4]: [Child process] Unhandled rejection error: fetch failed
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Completions][4]: [Child process] Unhandled rejection error: fetch failed
[Completions][4]: [Child process] Unhandled rejection error stack: TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by vivlimmsft** [comment] 2024-04-05 00:43
Closing as a duplicate of #491 for IntelliCode Completions, and #535 for IntelliCode C# Dev Kit, respectively.

**Closed by vivlimmsft** 2024-04-05 00:43 UTC
Labels: product-feedback, vscode-cdk, vscode-completions, reliability
