### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by elwynynion** [MicrosoftDocs/intellicode#391] opened 2022-07-10 14:04 UTC
**Unresponsive** It makes my VSCode slow.

- Issue Type: `Bug`
- Extension Name: `intellicode-api-usage-examples`
- Extension Version: `0.1.2`
- OS Version: `Windows_NT x64 10.0.21996`
- VS Code version: `1.69.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 273,
		"activateCallTime": 1,
		"activateResolvedTime": 392,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "VisualStudioExptTeam.intellicode-api-usage-examples",
				"_lower": "visualstudioexptteam.intellicode-api-usage-examples"
			},
			"activationEvent": "onLanguage:javascript"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by paustint** [comment] 2022-07-10 22:54
I have also noticed a lot of performance issues and tracked it down to, I think, this extension. The extension constantly shows up as "unresponsive" in the list of running extensions.

I tried to save some files and get the dialog letting me know that prettier is waiting for available CPU to format/save the files (because something else is using all resources).

When I looked at the process explorer, the extension running at 99% was intellicode-api-usage-examples - it normally slows things down for a while and then at some point frees up and things work good for a while. Normally changing branches or something where lots of files change is when I notice everything stop working (e.x. intellisense is stuck on loading for a long while)

but I have been unable to determine any reproducible steps or actions as it seems random when this happens, so I have been unable to produce a cpu profile.

![image](https://user-images.githubusercontent.com/5461649/178165130-d9bd4024-d6ff-492f-bcb9-d5a53a4cadd3.png)

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 218,
		"activateCallTime": 2,
		"activateResolvedTime": 20,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "VisualStudioExptTeam.intellicode-api-usage-examples",
				"_lower": "visualstudioexptteam.intellicode-api-usage-examples"
			},
			"activationEvent": "onLanguage:typescript"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by avimar** [comment] 2022-07-11 09:54
This just started happening to me yesterday - slow/no updates on syntax highlighting and pause on save. 

I tracked it down via the dev panel console:

```
 WARN Error: Aborted onWillSaveTextDocument-event after 1750ms
    at mainThreadSaveParticipant.ts:37:18
localProcessExtensionHost.ts:298 Extension Host
localProcessExtensionHost.ts:299 Debugger attached.
log.ts:301  INFO UNRESPONSIVE extension host: starting to profile NOW
log.ts:307  WARN UNRESPONSIVE extension host: 'VisualStudioExptTeam.intellicode-api-usage-examples' took 93% of 7215.024ms, saved PROFILE here: 'file:///c%3A/Users/Admin/AppData/Local/Temp/exthost-70b395.cpuprofile' 
```

**Comment by avimar** [comment] 2022-07-11 10:09
Sent file via email (9mb, not sure what private-ish info is in it.)

Device name	WIN10
Processor	Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor

**Comment by osobeso** [comment] 2022-07-11 11:07
Thanks @avimar 
By any chance, are you working with a react project? Or what's the codebase's language?

**Comment by avimar** [comment] 2022-07-11 11:58
@osobeso: Not react.

It's happening inside a restify@6 server side .js backend file (express-like).

**Comment by osobeso** [comment] 2022-08-19 22:01
Hi @avimar @paustint @elwynynion 
I'm happy to let you know that we have just published a new version of the extension that has some improvements to address the performance impact you were experiencing.

I will close the issue but please feel free to re-open if you are still experiencing this issue.

**Closed by osobeso** 2022-08-19 22:01 UTC
Labels: product-issue, python-api-usage-examples
